project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "un Sasso nello Stagno"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: La Villetta Comunale di Siderno.qmd
        text: La Villetta
      - href: L'Osservatorio del Verde Pubblico.qmd
        text: L'Osservatorio
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


resources:
  - /assets

