project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "un Sasso nello Stagno"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: La Villetta Comunale di Siderno.qmd
        text: "La Villetta"
      - href: Osservatorio del Verde Pubblico.qmd
        text: "L'Osservatorio"
      - href: about.qmd
        text: About

  sidebar:
    style: "docked"
    contents:
      - section: "La Villa Comunale"
        contents:
        - href: La Villetta Comunale di Siderno.qmd
        - href: gloci.qmd
        - href: areeverdi.qmd
        - href: analisi_costi.qmd
      - section: "Approfondimenti"
        contents:
        - href: damiani.qmd
      - section: "Attività"
        contents:
        - href: incontri.qmd
      - section: "Rassegna Stampa"
        contents:
        - href: rastamp.qmd
      - section: "Risorse Esterne"
        contents:
        - href: risest.qmd        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


resources:
  - /assets

