project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "un Sasso nello Stagno"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: index.qmd
        text: "La Villa"
      - href: Osservatorio del Verde Pubblico.qmd
        text: "L'Osservatorio"
      - href: about.qmd
        text: About

  sidebar:
    style: "docked"
    contents:
      - section: "La Villa Comunale"
        contents:
        - href: villa_pages/La Villa Comunale di Siderno.qmd
        - href: villa_pages/pnrr.qmd
        - href: villa_pages/pnrrbenicp.qmd
        - href: villa_pages/pnrr_verde.qmd
        - href: villa_pages/gloci.qmd
        - href: villa_pages/areeverdi.qmd
        - href: villa_pages/pertinenza.qmd
        - href: villa_pages/varianti.qmd
        - href: villa_pages/spese.qmd
        - href: villa_pages/analisi_costi.qmd

      - section: "Approfondimenti"
        contents:
        - href: villa_pages/damiani.qmd
      - section: "Attività"
        contents:
        - href: villa_pages/incontri.qmd
      - section: "Rassegna Stampa"
        contents:
        - href: villa_pages/rastamp.qmd
      - section: "Risorse Esterne"
        contents:
        - href: villa_pages/risest.qmd        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


resources:
  - /assets

