---
title: "La Villetta Comunale di Siderno"
---

Questa pagina tratta specificatamente dei Lavori in corso che mirano a riqualificare la Villetta Comunale e dintorni tanta cara ai sidernesi. 


### **PREMESSE**

Sono stati numerosi gli incontri per valutare l’impatto della “**Riqualificazione del Lungomare, della zona fronte Mare e della Villa Comunale della Città Di Siderno**” sull’ambiente, percepito ed effettivo. La  pubblica amministrazione si è mostrata sempre disponibile, ma per la complessità dei temi abordati il tempo è sempre venuto a mancarci e quindi sono sono sempre stati interrotti non permettendoci neanche di espolorare disgressioni a volte molto promettente.

Ii è allora naturalmente optato per pubblicare una pagian web disponibile a tutti che ciascuno può consultare come e quando meglio crede. Facilmente condivisibili nel caso si ritenesse utile farlo, rappresenta una opportunità di scovare nuove prospettive validi per valutare meglio il valore aggiunto degli interventi presente e futuri dal punto di vista strettamente ambientale, considerato il ruolo di protagonista indefettibile che il tema riveste nel Piano Nazionale della Riprese e Resilienza.

### **IL PIANO NAZIONALE DI RIPRESA E RESILIENZA.**

L'ambiente è oramai la priorità numero uno in tutte le programmazione a lungo termine ed è importante evidenziare la ratio soggiacente alla programmazione del PNRR; elencando gli obiettivi perseguiti:

- l'adattamento e la mitigazione del cambiamento climatico,
- favorire l'economia circolare,
- prevenire o ridurre l'inquinamento e
- proteggere o ripristinare la biodiversità e gli ecosistemi.

Per raggiungere questi scopi vengono finanziati degli investimenti a condizione che vengono rispettate delle normative di riferimento specifiche per ogni categoria d’investimento. Gli inerventi sul **verde** ricomprendono le seguenti disposizioni generali:

- comunitarie (Natura 2000, Direttive 92/43/CEE “Habitat”, 2009/147/CE “Uccelli”, ...),
- nazionali (testo unico ambientale D.lgs 152/06, Criteri Ambientali Minimi DM 63/2020, L.113/192 e successiva L. n. 10/2013 “norme per lo sviluppo degli spazi verdi urbani”) e
- regionali ove applicabili (LR Calabria 56/2019 e 7/2024)

Queste normative sono inderogabili per l'ottenimento del finanziamento. Se per esempio nell'amministrazione ordinaria l'applicazione della legge 10/2013 era discrezionale, **diventa obbligatoria nel contesto di un’opera finanziata dal PNRR**.

### **PNRR & LA TUTELLA DEI BENI CULTURALI E DEL PAESAGGIO.**

L’intervento di recupero della Villa Comunale potevA attingere a due tipologie d'investimento:

, 

1. il programma per valorizzare l'identità di luoghi: parchi e giardini storici (missione 1 comparto 3 investimento 2.3), 
2. il secondo con un progetto di rigenerazione urbana, volti a ridurre situazioni di emarginazione e degrado sociale (missione 5 comparto 2 investimento 2.1)

Il primo,  per le qualità che la villetta presentava come giardino storico, sembrava confezionato su misura, purtroppo l’art.6 co.3 dell’avviso pubblico determinava come soggetto ammissibile solo coloro che:

_Ai fini dell’ammissibilità saranno ritenuti validi sia i provvedimenti di tutela diretta sul giardino, sia quelli sull’immobile del quale il giardino è pertinenza, purché risulti evidente la sua rilevanza sotto il profilo storico-artistico._ **_Nel caso di beni di cui all’art. 10 comma 1 del D.Lgs. n. 42/2004 non saranno presi in considerazione quelli tutelati ope legis_** _o con procedimento di verifica dell’interesse culturale ai sensi dell’art. 12 del sopracitato decreto legislativo ancora non concluso_

In parole povere la villetta ricadrebbe automaticamente sotto la tutella dei beni culturali solo perchè realizzata da piu di 70 anni e perchè di proprietà dello stato e non per motivi qualitativi intrinsechi alla sua perculiarità artistica o bontanica non ancora ufficialmente evidenziati, attraverso una procedura di valutazione condotta dalla Soprintendenza.

Rimano allora, per finanziare l’intervento la seconda opzione; il programma riservati ai progetti di rigenerazione urbana. L'opportunità è probabilmente irrepetibile nel prossimo futuro, l’amministrazione comunale giustamente la coglie ed ottiene così il finanziamento per:

"LA RIGENERAZIONE DEGLI SPAZI URBANI PUBBLICI RICADENTI ALL’INTERNO DEL CENTRO ABITATO DI SIDERNO MARINA \*VIA DIVERSE\* RIQUALIFICAZIONE AREE VERDI." Per un importo complessivo di € 1.3 mln (CUP: I15F21000410001 – CIG: 9915740780).

La scheda descrittiva assegnata alla proposta di progetto disponibile<sup>[\[1\]](#footnote-1)</sup> sul sito “opencup.gov.it” classifica tutt’oggi il progetto nella tipologia RESTAURO e nella categoria "VERDE PUBBLICO".

Pare che comunque al Comune rimane sempre l’onere di conservarne le caratteristiche che contradistinguono la natura stessa della Villa Comunale se la qualifica di "restauro" abbia una connotazione vincolante e se la categoria "verde pubblico" determina un indirizzo preponderante de perseguire. In questo caso sarebbe saggio seguire quantomeno in parte le prescrizione delle LINEE GUIDA E NORME TECNICHE PER IL RESTAURO DEI GIARDINI STORICI curato dall’ APGI - ASSOCIAZIONE PARCHI E GIARDINI D’ITALIA per il Ministero della Cultura. Sono state redatte appositamente per conglobare tutti i tipi di parchi e giardini storici, dai più piccoli ai più principeschi, che rientrano nei finanziamenti del primo gruppo, esse contengono preziosi suggerimenti che possono definitavemente applicarsi alla gestione della nostra Villa Comunale, compresi i dettagli di tutte le fasi d’intervento sul verde, e gli eccellenti metodi di diagnostica preliminare indispensabili per un esito di successo.

### **TUTELLA DEL VERDE URBANO**

Una distinzione importante effettuata a monte fra i vari progetti finanziati sono quelli che mirano specificatamente ad una drastica riduzione d’emissione o di concentrazione del diossido di carbonio nell’atmosfera durante la loro fase di esercizio e quelli, simili a quello in oggetto, che **non la perseguono attivamente**. Per quest'ultimi **vige Il "regime 2".** molto più permissivo del regime 1. Tuttavia questo regime impone quantomeno il rispetto del principio di **“non arrecare danno significativo"** (Do Not Significantly Harm|DNSH) all’ambiente circostante. Tantevero che questo aspetto viene chiaramente richiamato dal progettista nella relazione tecnica a p.44 quando citta sia la L. N. 10/2013 “norme per lo sviluppo degli spazi verdi urbani” che le linee guide successivamente ufficializzate dal Ministero dell’Ambiente e della tutela del territorio e del mare nel 2017. Alcuni dei suoi concetti s’incrociano naturalmente con Linee guide dedicate specificamente ai Parchi e Giardini Storici citato precedentemente. Qui appresso si tenta di riassumerne i concetti più significativi in relazione con le opere in itinere condotte presso la Villa Comunale di Siderno.

La tutella del Verde Urbano è quindi resa obbligatoria al momento dell’adesione al programma d’investimento. I principi cardini della pianificazione del verde sono riassunti con **l’art. 6** **L.10/2013 che prevede**:

1. **il rinverdimento** per le nuove costruzione e ristrutturazione edilizia significativa.
2. **L’incremento, la conservazione e la tutela del patrimonio arboreo** per gli edifici esistenti
3. La raccolta efficace delle acque piovane, **efficienza energetica**,
4. riduzione effetto isola di calore, formazione del personale addetto ai lavori,
5. sensibilizzazione della cittadinanza

mentre **l’art.7 estende l’applicazione delle prescrizioni non solo all’albero monumentale ma a tutte le alberature che rispondono ai seguenti criteri:**

- **alberi ad alto fusto singoli** in ambiente naturali o artificiali che presentano caratteristiche fisiche straordinarie oppure caratteristiche storiche culturale rilevanti
- **i filari o alberate di particolare pregio paesaggistico**, monumentale, storico e culturale, ivi compresi quelli inseriti nei centri urbani
- **gli alberi ad alto fusto inseriti in particolari complessi architettonici** di importanza storica e culturale, quali ad esempio **ville**, monasteri, chiese, **orti botanici** e **residenze storiche private.**

Eventualmente se si desidera approfondire la tematica, è allegato un riassunto dell’intervento curato del Dott. Giovani Damiani, chimico e biologo, all’occasione del seminario “_Giardini Storici: la tutela dopo il PNRR_” (All.to n°01). Il dott. Damiani ha anche contribuito alla stesura delle “L_inee guida e norme tecniche per il restauro dei giardini storici”_ già citato. Le informazioni condivise dalla sua esperienza attrezzeranno adeguatamente il lettore per capire le problematiche di fondo a seguire.

Ad esempio, le considerazioni riguardo le superfici vegetali individuate a terra da sole sono insufficienti a valutarne il contributo ecologico di un ecosistema complesso. Sono da considerare anche il suolo nel suo intero spesso e le sue qualità agronomiche come anche il volume complessivo della canopea.

**Per quanto riguarda la preservazione del suolo**, edotti delle nozioni elementari presente nel riassunto, si può facilmente intuire perché la pavimentazione in prossimità delle radici dei ficus monumentali sia fortemente sconsigliata; **intralcia i meccanismi di scambio** tra habitat adiacenti. Ad esempio impedisce l’accumulo naturale di sostanza organica come ad esempio le stesse foglie autunnali che migliorano il terreno proteggendolo dagli sbalzi termici e contribuiscono allo sviluppo dei microrganismi quali funghi simbionti e micorrize. Il fenomeno è così flagrante che in alcuni giardini è espressamente vietato l’asportazione di sostanza organica dal terreno così mettere a nudo l’apparato radicale oppure l’interramento eccessivo, tutti possono provocare degli squilibri nella rizosfera tali da addirittura distruggere quel microcosmo delicato indispensabile come il microbiota umano.

Persino la premura di utilizzare un vespaio areato (sistema tipo cupolex) non controbilancia tutte le contro indicazioni succitate. Anzi se consideriamo il caso straordinario in cui avvenisse per ipotesi una mareggiata: l’acqua salata del mare inonderebbe l’intercapedine d’aria sistemata per garantire l’aerazione in tempi normali, quanto tempo ci vorrebbe perché il sale accumulato nel terreno fosse portato via dal deflusso naturale delle acque piovane o d’irrigazione verso gli strati più profondi se vengono impedite dalla pavimentazione soprastante.

Tra l’altro questa sistemazione rialzata andrebbe a ridurre ancora di più l’altezza libera sotto i rami di questi alberi monumentali già bassi.

**Per quanto riguarda la canopea**, è la parte attiva sede della preziosa fotosintesi che converte il diossido di carbonio in ossigeno. Questo processo chimico è fortemente endotermico, l’evaporazione acquea contribuisce al raffrescamento come se fossero operativi dai 5 ai 10 condizionatori d’aria per 20 ore al giorno, senza consumo elettrico. Il dato è di vitale importanza quando si decide di tagliare o spostare un albero, anche per quelli rimanente perché con l’aumentare della temperatura media circostante l’efficacia del processo di conversione s’indebolisce, meno fotosintesi, meno evaporazione e a sua volta nuovo aumento di temperature, sono i temuti cicli di feedback positivi nella dinamica dei sistemi, più comunamente chiamati circoli viziosi. Ecco spiegato rapidamente uno dei motivi soggiacente **a favore dell’aggregazione del verde pubblico: diventa più resiliente al riscaldamento climatico e sicuramente più piacevole per la cittadinanza**.

Alla luce di quanto appena trattato e dall’osservazione della raccolta di fotografie satellitare che ritraccia sommariamente l’evoluzione della canopea della Villa Comunale dal 2010 ad oggi, si osserva una netta diminuzione della stessa, che sia per inasprimento del clima o per manutenzioni inadeguata o del tutto assente come più volte specificato da diverse parti, la situazione è purtroppo questa. Ora la domanda è: la riqualificazione proposta rimedia o rinforza questa tendenza?

**Per quanto riguarda l’aspetto botanico**, la rimozione di alberature circostante porterebbe come altro effetto negativo la forte probabilità che i ficus andassero ad occupare lo spazio “vitale” adesso liberato, estendendo anco di più i loro rami verso mare o il sole. L’allungamento aumenterà il carico per effetto leva su una chioma che mostra un inizio di dissimmetria con tutte le conseguenze nel tempo. Oltretutto l’allargamento della chioma ricoprirà maggiormente l’area che il progetto riserva alla piazza quando l’altezza disponibile sotto i rami ne limitava già la fruizione prima dei lavori. Bisogna tenere conto che quei alberi sono dei ficus tipo magnolioide, alberi sempreverde tra quelli più grandi tra i alberi di fico coltivati, crescono da 22 a 55 metri in altezza e da 21 a 40 metri in larghezza, a ragione di 90 cm in media l’anno, fino ad una venerabile età di 150 anni.

A parere del comitato, per tutti i motivi sopracitati in un ambito di restauro del verde pubblico, così come viene classificato l’intervento nella scheda riassuntiva della proposta finanziata, le alberature avrebbero dovute essere rispristinate. Se era emerso a suo tempo delle valide motivazioni a rimuoverli, era indispensabile oggi individuarne il motivo per cui si era reso necessario tale rimozione, e possibilmente rimediandone le causa d’origine per la salute avvenire della Villa; immaginiamo che il taglio fosse stato reso necessario a causa di patologie o altri impedimenti, queste informazioni costituivano già un indizio di notevole importanza per assestare e trattare l’ambiente perché potesse finalmente offrire delle condizioni di sviluppo migliori. Nella stessa ottica il comitato suggerisce fortemente che non venga pavimentata la superficie corrispondente all’estensione delle chiome soprastante.

Per sostenere ulteriormente le nostre tesi, il comitato ha individuato alcuni punti essenziali estrapolati dalle **Linee guida per la gestione del verde urbano e prime indicazioni per una pianificazione sostenibile,** per ognuno di essi sono evidenziati alcuni motivi, secondo il nostro umile parere, per i quali andrebbe rivisitata la proposta progettuale, ben inteso nel limite del possibile, oppure mettere i suggerimenti a dimora per i prossimi interventi.

I criteri di realizzazione di aree verdi ritenuti più attinente alla presente vicenda sono:

- priorità **inserimento** nel sistema del verde urbano esistente
  -  <span style="color:red;">La morfologia del verde urbano esistente, dalla raccolta delle fotografie satellitare degli anni precedenti, è stata profondamente alterata dalla compenetrazione urbana realizzata, gli alberi che componevano il filare frontistante agli alberi monumentali erano stati tagliati persino persino prima del rilievo e sostituti da quelli progettati a ridosso della tribuna nord allontanandoli dalla loro posizione originale all’interno della Villa Comunale.</span>
- Massimizzare **accorpamento** per evitare frammentazioni e collocazione residuali
  - <span style="color:red;">L’aggiunta della vegetazione è stata realizzata principalmente ad isola, distanziate dal fulcro vegetale originario in periferia
- Usi materiali ecocompatibile e **riciclati e riciclabile** che possono essere facilmente demoliti e riutilizzati o riciclati al termine dell’uso,</span>
  - <span style="color:red;">Il cemento armato utilizzato per la costruzione delle tribune non rientra in questa descrizione soprattutto nella fase di remissione, infatti all’inizio del cantiere è stata difficoltosa la rimozione dei blocchi di cemento inseriti dai pregressi interventi, sono dovuti intervenire di grossa potenza col rischio di creare una eccessiva compattazione dele terreno vegetale.</span>
- **Biodiversità**; composizioni vegetali miste rispetto a quelle in purezza, utilizzando specie che permettano l’alimentazione e il rifugio per insetti, uccelli e piccoli mammiferi e dell’avifauna
  - <span style="color:red;">Sono stati previsti d’inseriti solamente le classiche palme, sarebbe stato auspicabile aggiungere essenze aromatiche per allontanare insetti attratti dalla futura illuminazione per la comodità degli spettatori</span>
- Gestione acque pluviali (vasche, bacini di ritenzione, fossati inondabili)
  - <span style="color:red;">Il dimensionamento dell’impianto di recupero dell’acque piovane è stato dimensionato solamente per garantire la gestione delle piogge “di intensità fino a mm 7 che equivale al valore medio nei peridi estivi per la città di Siderno. Superati questi valori limite le acque piovane in esubero verranno smaltite tramite rete comunale delle acque di raccolta pubbliche” (p.7 tav 01.1- Relazione specialistica dei sottosistemi a rete). Quando normalmente il sistema di recupero con le vasche di accumulo andrebbe dimensionato in funzione delle precipitazioni annue, in particolare di quelle più intense, proprio per poterle ridistribuire nei momenti più arridi.</span>
- **Gestione suoli**: preservare la fertilità del suolo adottando tutte gli accorgimenti per conservare e migliorare le caratteristiche chimiche, fisiche e la componente biologica del terreno;
  - **analisi del terreno,**
    - <span style="color:red;">risulta mancante qualsiasi analisi del terreno in merito alle caratteristiche su elencate</span>
  - **gestione movimenti e accantonamento dei primi strati vegetali del terreno,**
    - <span style="color:red;">sono assenti indicazioni specifiche sulla gestione dei primi strati vegetali del terreno</span>
- **Rilievo in scala adeguata di tutti gli elementi biotici ed abiotici**
  - <span style="color:red;">Sono stati rappresentati in pianta solamente gli alberi monumentali escludendo il resto della vegetazione arborea e arbustiva</span>
- **Tabella con il calcolo della superficie di copertura arborea, arbustiva e erbacea**. Oltre a questo sarà necessario elaborare una stima della copertura arborea a 25 anni dal collaudo.
  - <span style="color:red;">Dagli elaborati pubblicati all’albo pretorio non risultano rilevati o indicati questi dati</span>
- **Calcolo del fabbisogno idrico annuale stimato**
  - <span style="color:red;">Mancando i dati precedenti, il fabbisogno non può essere determinato con sufficiente precisione, era anche un dato necessario per il dimensionamento dell’impianto di recupero delle acque piovane citato prima.</span>

Il comitato pensa che sono valutazioni fondate su ragionamenti e dati slegati dall’apprezzamento estetico, e quindi perfettamente obbiettivi, che trovano fondatezza nel quadro normativo imposto dal principio cardine **“di non recare danni significativi”** all’ambiente. Ed è per questo motivo che s'invita la pubblica amministrazione a valutarle attentamente le proposte di variante e trarne gli apsetti migliori, nell’interesse della Villa Comunale e della cittadinanza. **La riqualificazione va fatta al meglio delle risorse disponibili, finanziarie, materiali ed intellettuali.**

### AMMISSIBILITA DI PROPOSTE DI VARIANTE IN CORSO D'OPERA

Diverse volte ci è stato ripetuto l’impossibilità di travolgere un progetto di opere pubbliche approvato e finanziato, tuttavia in passato in alcuni casi di forza maggiore l’accoglimento di una richiesta di variante in corso d’opera sono state positive se determinati requisiti erano riuniti:

- Cantieristico: non comportino un aumento significativo dei costi (15%) o un allungamento eccessivo dei tempi di esecuzione dell'opera
- Motivazione: Le varianti devono essere giustificate da ragioni tecniche, economiche o di pubblico interesse.
- Conformità normativa: Le varianti non devono contravvenire alle normative vigenti, comprese quelle in materia di sicurezza, di tutela ambientale e di diritti dei lavoratori.
- Concorrenza: Le varianti devono essere oggetto di una valutazione comparativa tra le diverse proposte e non devono alterare in maniera sostanziale i termini della gara d'appalto.
- Autorizzazione: Le varianti devono essere approvate dall'ente appaltante e, se necessario, autorizzate dagli organi competenti.

Per l’individuazione delle spese necessari per eventualmente attuare modifiche, sono state esaminate rapidamente le voci del computo metrico, dell’elenco prezzi, dell’analisi dei prezzi e del prezzario regionale della regione Calabria 2023, e le speso si ripartiscono mediamente così:

<table><tbody><tr><th><ul><li>opere paesaggistiche (€ 61.000) e</li><li>arredi (€ 52.000)</li></ul></th><th><ul><li>pavimentazione (€ 325.669)</li><li>parcheggio (€ 295.791)</li><li>tribune (€ 221.225)</li><li>illuminazione (€ 236.792)</li></ul></th></tr></tbody></table>

dal quale emerge accessoriamente che circa solo il 10% delle somme erogate sono dedicate alle opere paesaggistiche (€ 61.000) e arredi (€ 52.000) mentre il restante 90 % alle opere “artificiali”, una disparità considerevole confermata dalle percentuali documentate nel contratto d’appalto a p.3.

Se chiedere un percentuale maggiore per le spese dedicate al verde sarebbe anche legittimo, rimane pur sempre più realistico richiedere quantomeno che lo sviluppo della parte minerale non pregiudichi minimamente su quella parte vegetativa.

Comunque nel caso in cui accogliate le nostre richieste valutandone i benefici sul lungo termine, accessoriamente per recuperare margini di manovra è stato reperito **un esubero di spese di circa €130.000,00** in sole due voci, è nel caso non fossero sufficienti, sono stati identificati, prima che fossero gettate le tribune, altre proposte di varianti che potessero allo stesso tempo diminuire alcune voci di spese migliorando anche l’impronta ecologica complessiva del progetto, di seguito una **raccolta veloce di suggerimenti emessi durante i vari incontri del comitato**:

**PER LE TRIBUNE**

Per quanto riguarda la Tribuna Nord, si pensa che le dimensioni potevano essere più contenute, con un raggio minore, un’apertura più stretta e una gradinata in meno, grazie ai dislivelli si poteva integrare meglio. Le alternative a farle piene ed in cemento armato erano numerose, vero che ci è stato specificato che il cemento adoperato è “green” – dimezza l’emissione di diossido di carbonio – ma in un contesto naturalistico, materiali sostitutivi di minore impatto ecologico e di più semplice rimozione a fine ciclo sono tanti, a cominciare

**L’IMPIANTO DI ILLUMINAZIONE**

Sicuramente l’impianto d’illuminazione verifica tutti i parametri per la comodità e la sicurezza dei futuri utenti, le schede sul funzionamento delle apparecchiature è dettagliatissima, mancano per le valutazioni riguardo gli effetti sul fotoperiodo delle piante e sui ritmi circadiani dalla fauna e dei cittadini (i LED possono emettere “luce blu”).

È da valutare l’utilità effettiva delle due torri di luce previste in origine per illuminare dall’alto la scena centrale dell’anfiteatro essendo coperta dalla chioma degli alberi monumentali centrale che ostacolerebbero la luce.

**L’IMPIANTO D’IRRIGAZIONE**

Sono stati suggeriti l’uso di un sistema d’irrigazione a gocce e un sistema di nebulizzazione, delle fontane funzionante, per quanto riguarda la gestione del recupero delle acque sono già state espressi i dubbi.

**L’IMPIANTO DI DIFFUSIONE ACUSTICA**

L’utenza, come comunità è già inondata da flussi di dati e informazione continui, ci si chiede se non fosse il caso di riservare un’oasi di prossimità dove i cittadini possono estraniarsi momentaneamente. Un posto dove sottrarsi a quello che oggi viene denominato come **infotossicazione**. Quale ambiente migliore della Villa Comunale, dove un panorama sonoro naturale garantirebbe questa evasione temporanea grazie ad un ecosistema vegetativo naturale vivo, vero e sano (insetti, avifauna, vento nelle foglie, rumore del mare possibilmente privi del rombo dei veicoli), sperando che non capiti mai una “primavera silenziosa” senza l’ausilio di surrogati digitali quando abbiamo la possibilità di avere concretamente il luogo adatto.

I CHIARIMENTI

È stata portata a conoscenza del comitato che:

- - Il comitato comunicava che la riqualificazione comportava la diminuzione del 42% di superficie vegetativa sulla base della tavola 7.3 Superficie permeabili durante l’evento del 24 maggio 2024 tenutasi all’YMCA. il R.U.P. l’Ing. Surace ha rimarcato che sono state identifica più dettagliatamente le reali superfici, per natura ed estensione specifiche, nella tavola 7.2.8 non ancora pubblicata al momento dell’incontro. Dal rilievo risulterebbe allora un’estensione ante operam del tappetto vegetale di molto inferiore a quanto indicato nella tavola 7.3. A lavori compiuti come da progetto dovrebbe esserci addirittura un aumento della superficie vegetale finale.
- Sono stati individuati e repertoriati gli alberi monumentali perché godano di tutte le misure di salvaguardia disposte per leggi, e che gli altri esemplari ad alto fusto sono stati trapiantati ove necessario con tutte le dovute cure,
- il cemento adoperato è un cemento rispettoso dell’ambiente in quanto il suo utilizzo emette il 50% in meno di diossido di carbonio e che non sono stati introdotti quantitativi aggiuntivi a quelli rimossi dagli interventi pregressi, al contrario.
- che la pavimentazione utilizzata è fortemente drenante per permettere alle acque di percolare nel terreno soggiacente o di essere raccolte nelle apposite vasche di accumulo.

Il comitato “sasso nello stagno” ha poi rimarcato che:

- Dato che la tavola sarà messa a disposizione per studiarla, ci si riserva di rispondere una volta esaminata con cura. \[comunque dal rilievo fotografico le uniche superfici non inverdite sono le rampe e le scale in cemento così come le aere destinate al transito pedonale ricoperte di ghiaia\]
- il rilevamento degli alberi monumentali esistenti è sicuramente un’ottima iniziativa, ma che andrebbe integrata con le disposizioni dell’art.7 della L 10/2013 che estende la monumentalità a tutti gli alberi che compongono la vegetazione arborea della villa,
- il cemento più ecologico è quello che non si usa e che c’erano sicuramente soluzioni costruttive che potevano ridurne considerevolmente l’impiego assecondando maggiormente gli obbiettivi fissati dai Criteri Ambientali Minimi (C.A.M.).
- Seppure la pavimentazione drenante può presentare delle permeabilità migliore dei terreni naturali, non possiede sicuramente lo stesso potenziale biologico e costituisce invariabilmente uno strato di isolamento riguardo alcuni processi di scambio (ossigeno, nutrienti, concimi, etc… ) tra habitat contigui soprattutto in prossimità degli apparati radicali appartenenti ai ficus centrali

1. all'indirizzo: <https://www.opencup.gov.it/portale/it/web/opencup/home/progetto/-/cup/I15F21000410001> [↑](#footnote-ref-1)