---
title: "La Riqualificazione della Villa Comunale di Siderno"
---

Questa pagina tratta specificatamente dei Lavori in corso che mirano a riqualificare la Villa Comunale e dintorni tanta cara ai sidernesi. 
Come al solito ogni vento di cambiamento porta con se maree di osservazioni e commenti


## **PREMESSE**

Sono stati numerosi gli incontri per valutare l’impatto della “**Riqualificazione del Lungomare, della zona fronte Mare e della Villa Comunale della Città Di Siderno**” sull’ambiente, percepito ed effettivo. La  pubblica amministrazione si è mostrata sempre disponibile, ma per la complessità dei temi abbordati, il tempo è sempre venuto a mancare, interrompendo sistematicamente gli [incontri](incontri.qmd), a volte anche nei momenti più promettenti quando inizialmente sembravano solamente disgressioni esplorative.

La redazione di una pagina web si è naturalmente imposta come soluzione ideale per rendere disponibile a tutti le tematiche abbordate che ciascuno può consultare come e quando meglio crede. Il contenuto è facilmente condivisibili nel caso si ritenesse utile farlo, e rappresenta una opportunità di scovare nuove valide prospettive per valutare meglio il valore aggiunto degli interventi presente e futuri dal punto di vista strettamente ambientale, considerato il ruolo di protagonista indefettibile che il tema riveste nel Piano Nazionale della Riprese e Resilienza.

La mole di informazioni recuperate si è addensata col passare del tempo, perciò si è deciso di indicare come leggere il più efficacemente possibili questo minisito. Il comitato "un sasso nello stagno" vuole evidenziare che lo stato di progetto proposto non rispetta le norme che tutelano l'ambiente in questa circostanza. Affermare gratuitamente una cosa del genere sarebbe irrispettoso di tutti coloro che hanno lavorato a cambiare il volto di Siderno con a cuore le migliori intenzioni.  Per iniziare preparati questa lettura, dobbiamo affrontare tematiche non sempre appassionanti.

I primi tre punti concernano il quadro normativo

 Gli obiettivi ed il quadro normativo del PNRR

I due seguenti sono una specie di diagnostica dei luoghi condotta con immagini recuperate da fonti diverse, alcun facilmente identificabili, per cercare di ritracciare l'evoluzione storico del luogo e vedere se puo essere d'aiuto

Il quinto sarebbe il punto clu della contestazione, esamina il motivo principale per cui il comitato si è inizialmente formato, prima come lieve sospetto e poi confermato dalla documentazione pubblicata fino ad oggi

Il sesto punto propone delle varianti, perchè quando si vuole criticare l'operato di qualcuno e lo si vuole fare costruttivamente non solo per spirito di contradizione, offrire delle soluzioni è un contributo molto importante.

Il settimo punto è l'analisi dei costi affrontati, è stato condotto sempre nello spirito di quantificare le modifiche proposte e cercare di non sforare con soluzioni troppo fantasiose che sarebbero rimaste insoddisfatte in partenza

Tutte queste pagine sono quindi facilmente accessibili dal menu a sinistra sui desktop, sul popup a scomparsa un alto a sinistra sui dispositivi mobili.

## **IL PIANO NAZIONALE DI RIPRESA E RESILIENZA.**

## **PNRR & LA TUTELLA DEI BENI CULTURALI E DEL PAESAGGIO.**

## **LA TUTELLA DEL VERDE URBANO NELL'AMBITO DELL PNRR**

## **LA PERTINENZA DEL PROGETTO**

## **le varianti**

## **ANALISI DEI COSTI**

## **I CHIARIMENTI**







