<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>un Sasso nello Stagno - La Villetta Comunale di Siderno</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">un Sasso nello Stagno</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./La Villetta Comunale di Siderno.html" aria-current="page"> 
<span class="menu-text">La Villetta</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Osservatorio del Verde Pubblico.html"> 
<span class="menu-text">L’Osservatorio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#premesse" id="toc-premesse" class="nav-link active" data-scroll-target="#premesse"><strong>PREMESSE</strong></a></li>
  <li><a href="#il-piano-nazionale-di-ripresa-e-resilienza." id="toc-il-piano-nazionale-di-ripresa-e-resilienza." class="nav-link" data-scroll-target="#il-piano-nazionale-di-ripresa-e-resilienza."><strong>IL PIANO NAZIONALE DI RIPRESA E RESILIENZA.</strong></a></li>
  <li><a href="#pnrr-la-tutella-dei-beni-culturali-e-del-paesaggio." id="toc-pnrr-la-tutella-dei-beni-culturali-e-del-paesaggio." class="nav-link" data-scroll-target="#pnrr-la-tutella-dei-beni-culturali-e-del-paesaggio."><strong>PNRR &amp; LA TUTELLA DEI BENI CULTURALI E DEL PAESAGGIO.</strong></a></li>
  <li><a href="#tutella-del-verde-urbano" id="toc-tutella-del-verde-urbano" class="nav-link" data-scroll-target="#tutella-del-verde-urbano"><strong>TUTELLA DEL VERDE URBANO</strong></a></li>
  <li><a href="#ammissibilita-di-proposte-di-variante-in-corso-dopera" id="toc-ammissibilita-di-proposte-di-variante-in-corso-dopera" class="nav-link" data-scroll-target="#ammissibilita-di-proposte-di-variante-in-corso-dopera"><strong>AMMISSIBILITA DI PROPOSTE DI VARIANTE IN CORSO D’OPERA</strong></a></li>
  <li><a href="#analisi-dei-costi" id="toc-analisi-dei-costi" class="nav-link" data-scroll-target="#analisi-dei-costi"><strong>ANALISI DEI COSTI</strong></a>
  <ul class="collapse">
  <li><a href="#le-tribune" id="toc-le-tribune" class="nav-link" data-scroll-target="#le-tribune"><strong>LE TRIBUNE</strong></a></li>
  <li><a href="#limpianto-di-illuminazione" id="toc-limpianto-di-illuminazione" class="nav-link" data-scroll-target="#limpianto-di-illuminazione"><strong>L’IMPIANTO DI ILLUMINAZIONE</strong></a></li>
  <li><a href="#limpianto-dirrigazione" id="toc-limpianto-dirrigazione" class="nav-link" data-scroll-target="#limpianto-dirrigazione"><strong>L’IMPIANTO D’IRRIGAZIONE</strong></a></li>
  <li><a href="#limpianto-di-diffusione-acustica" id="toc-limpianto-di-diffusione-acustica" class="nav-link" data-scroll-target="#limpianto-di-diffusione-acustica"><strong>L’IMPIANTO DI DIFFUSIONE ACUSTICA</strong></a></li>
  </ul></li>
  <li><a href="#i-chiarimenti" id="toc-i-chiarimenti" class="nav-link" data-scroll-target="#i-chiarimenti"><strong>I CHIARIMENTI</strong></a></li>
  <li><a href="#rassegna-stampa" id="toc-rassegna-stampa" class="nav-link" data-scroll-target="#rassegna-stampa"><strong>RASSEGNA STAMPA</strong></a></li>
  <li><a href="#rissorse-esterne" id="toc-rissorse-esterne" class="nav-link" data-scroll-target="#rissorse-esterne"><strong>RISSORSE ESTERNE</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">La Villetta Comunale di Siderno</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Questa pagina tratta specificatamente dei Lavori in corso che mirano a riqualificare la Villetta Comunale e dintorni tanta cara ai sidernesi.</p>
<section id="premesse" class="level2">
<h2 class="anchored" data-anchor-id="premesse"><strong>PREMESSE</strong></h2>
<p>Sono stati numerosi gli incontri per valutare l’impatto della “<strong>Riqualificazione del Lungomare, della zona fronte Mare e della Villa Comunale della Città Di Siderno</strong>” sull’ambiente, percepito ed effettivo. La pubblica amministrazione si è mostrata sempre disponibile, ma per la complessità dei temi abbordati, il tempo è sempre venuto a mancare, interrompendo sistematicamente gli <a href="./incontri.html">incontri</a>, a volte anche nei momenti più promettenti quando inizialmente sembravano solamente disgressioni esplorative.</p>
<p>La redazione di una pagina web si è naturalmente imposta come soluzione ideale per rendere disponibile a tutti le tematiche abbordate che ciascuno può consultare come e quando meglio crede. Il contenuto è facilmente condivisibili nel caso si ritenesse utile farlo, e rappresenta una opportunità di scovare nuove valide prospettive per valutare meglio il valore aggiunto degli interventi presente e futuri dal punto di vista strettamente ambientale, considerato il ruolo di protagonista indefettibile che il tema riveste nel Piano Nazionale della Riprese e Resilienza.</p>
</section>
<section id="il-piano-nazionale-di-ripresa-e-resilienza." class="level2">
<h2 class="anchored" data-anchor-id="il-piano-nazionale-di-ripresa-e-resilienza."><strong>IL PIANO NAZIONALE DI RIPRESA E RESILIENZA.</strong></h2>
<p>L’ambiente è oramai la priorità numero uno in tutte le programmazione a lungo termine ed è importante evidenziare la ratio soggiacente alla programmazione del PNRR; elencando gli obiettivi perseguiti:</p>
<ul>
<li>l’adattamento e la mitigazione del cambiamento climatico,</li>
<li>favorire l’economia circolare,</li>
<li>prevenire o ridurre l’inquinamento e</li>
<li>proteggere o ripristinare la biodiversità e gli ecosistemi.</li>
</ul>
<p>Per raggiungere questi scopi vengono finanziati degli investimenti a condizione che vengono rispettate delle normative di riferimento specifiche per ogni categoria d’investimento. Gli interventi sul <strong>verde</strong> ricomprendono spesso le seguenti disposizioni generali:</p>
<ul>
<li>comunitarie (Natura 2000, Direttive 92/43/CEE “Habitat”, 2009/147/CE “Uccelli”, …),</li>
<li>nazionali (testo unico ambientale D.lgs 152/06, Criteri Ambientali Minimi DM 63/2020, L.113/192 e successiva L. n.&nbsp;10/2013 “norme per lo sviluppo degli spazi verdi urbani”) e</li>
<li>regionali ove applicabili (LR Calabria 56/2019 e 7/2024)</li>
</ul>
<p>Queste normative sono inderogabili per l’ottenimento del finanziamento. Se per esempio nell’amministrazione ordinaria l’applicazione della legge 10/2013 era discrezionale, <strong>diventa obbligatoria nel contesto di un’opera finanziata dal PNRR</strong>.</p>
</section>
<section id="pnrr-la-tutella-dei-beni-culturali-e-del-paesaggio." class="level2">
<h2 class="anchored" data-anchor-id="pnrr-la-tutella-dei-beni-culturali-e-del-paesaggio."><strong>PNRR &amp; LA TUTELLA DEI BENI CULTURALI E DEL PAESAGGIO.</strong></h2>
<p>L’intervento di recupero della Villa Comunale poteva attingere a due tipologie d’investimento:</p>
<p>,</p>
<ol type="1">
<li>il programma per valorizzare l’identità di luoghi: parchi e giardini storici (missione 1 comparto 3 investimento 2.3),</li>
<li>il secondo con un progetto di rigenerazione urbana, volti a ridurre situazioni di emarginazione e degrado sociale (missione 5 comparto 2 investimento 2.1)</li>
</ol>
<p>Il primo, per le qualità che la villetta presentava come giardino storico, sembrava confezionato su misura, purtroppo l’art.6 co.3 dell’avviso pubblico determinava come soggetto ammissibile solo coloro che:</p>
<p><em>Ai fini dell’ammissibilità saranno ritenuti validi sia i provvedimenti di tutela diretta sul giardino, sia quelli sull’immobile del quale il giardino è pertinenza, purché risulti evidente la sua rilevanza sotto il profilo storico-artistico.</em> <strong><em>Nel caso di beni di cui all’art. 10 comma 1 del D.Lgs. n.&nbsp;42/2004 non saranno presi in considerazione quelli tutelati ope legis</em></strong> <em>o con procedimento di verifica dell’interesse culturale ai sensi dell’art. 12 del sopracitato decreto legislativo ancora non concluso</em></p>
<p>In parole povere la villetta ricadrebbe automaticamente sotto la tutela dei beni culturali solo perché realizzata da più di 70 anni e perché di proprietà dello stato e non per motivi qualitativi intrinsechi alla sua peculiarità artistica o botanica, se esistono non sono state ancora ufficialmente evidenziate, attraverso una procedura di valutazione condotta dalla Soprintendenza.</p>
<p>Rimane allora, per finanziare l’intervento, la seconda opzione; il programma riservati ai progetti di rigenerazione urbana. L’opportunità è ottima e probabilmente irrepetibile nel prossimo futuro, l’amministrazione comunale giustamente la coglie ed ottiene così il finanziamento per:</p>
<p>“LA RIGENERAZIONE DEGLI SPAZI URBANI PUBBLICI RICADENTI ALL’INTERNO DEL CENTRO ABITATO DI SIDERNO MARINA *VIA DIVERSE* RIQUALIFICAZIONE AREE VERDI.” Per un importo complessivo di € 1.3 mln (CUP: I15F21000410001 – CIG: 9915740780).</p>
<p>La scheda descrittiva assegnata alla proposta di progetto disponibile sul sito “<a href="https://www.opencup.gov.it/portale/it/web/opencup/home/progetto/-/cup/I15F21000410001">opencup.gov.it</a>” classifica però tutt’oggi il progetto nella tipologia RESTAURO e nella categoria “VERDE PUBBLICO”.</p>
<p>Se la qualifica di “restauro” abbia una connotazione vincolante e se la categoria “verde pubblico” determina un indirizzo preponderante de perseguire, pare che rimanga sempre l’onere alla stazione appaltante di conservarne le caratteristiche che contraddistinguono la natura stessa della Villa Comunale. In questo caso saggia sarebbe l’osservanza delle prescrizioni contenute nelle <strong>LINEE GUIDA E NORME TECNICHE PER IL RESTAURO DEI GIARDINI STORICI</strong> curato dall’ APGI - ASSOCIAZIONE PARCHI E GIARDINI D’ITALIA per il Ministero della Cultura. Sono state redatte appositamente per trattare tutti i tipi di parchi e giardini storici, dai più piccoli ai più principeschi, che rientrano nei finanziamenti del primo gruppo, esse contengono preziosi suggerimenti che possono definitivamente applicarsi alla gestione della nostra Villa Comunale, compresi i dettagli di tutte le fasi d’intervento sul verde, e gli eccellenti metodi di diagnostica preliminare indispensabili per un esito di successo.</p>
</section>
<section id="tutella-del-verde-urbano" class="level2">
<h2 class="anchored" data-anchor-id="tutella-del-verde-urbano"><strong>TUTELLA DEL VERDE URBANO</strong></h2>
<p>Un’altra distinzione importante effettuata a monte fra i vari progetti finanziati sono quelli che mirano specificatamente ad una drastica riduzione d’emissione o di concentrazione del diossido di carbonio nell’atmosfera durante la loro fase di esercizio e quelli, simili a quello in oggetto, che <strong>non la perseguono attivamente</strong>. Per quest’ultimi vige Il <strong>“regime 2”.</strong> molto più permissivo del regime 1. Tuttavia questo regime impone quantomeno il rispetto del principio di <strong>“non arrecare danno significativo”</strong> (Do Not Significantly Harm|DNSH) all’ambiente circostante. Tant’è vero che questo aspetto viene chiaramente richiamato dal progettista nella relazione tecnica a p.44 quando citta sia la L. N. 10/2013 “norme per lo sviluppo degli spazi verdi urbani” che le linee guide successivamente ufficializzate dal Ministero dell’Ambiente e della tutela del territorio e del mare nel 2017. Alcuni dei suoi concetti s’incrociano naturalmente con Linee guide dedicate specificamente ai Parchi e Giardini Storici citato precedentemente. Qui appresso si tenta di riassumerne alcuni tra i più significativi in relazione con le opere in itinere condotte presso la Villa Comunale di Siderno.</p>
<p>La tutela del Verde Urbano è quindi resa obbligatoria al momento dell’adesione al programma d’investimento. I principi cardini della pianificazione del verde sono riassunti con <strong>l’art. 6</strong> <strong>L.10/2013 che prevede</strong>:</p>
<ol type="1">
<li><strong>il rinverdimento</strong> per le nuove costruzione e ristrutturazione edilizia significativa.</li>
<li><strong>L’incremento, la conservazione e la tutela del patrimonio arboreo</strong> per gli edifici esistenti</li>
<li>La raccolta efficace delle acque piovane, <strong>efficienza energetica</strong>,</li>
<li>riduzione effetto isola di calore, formazione del personale addetto ai lavori,</li>
<li>sensibilizzazione della cittadinanza</li>
</ol>
<p>mentre <strong>l’art.7 estende l’applicazione delle prescrizioni non solo all’albero monumentale ma a tutte le alberature che rispondono ai seguenti criteri:</strong></p>
<ul>
<li><strong>alberi ad alto fusto singoli</strong> in ambiente naturali o artificiali che presentano caratteristiche fisiche straordinarie oppure caratteristiche storiche culturale rilevanti</li>
<li><strong>i filari o alberate di particolare pregio paesaggistico</strong>, monumentale, storico e culturale, ivi compresi quelli inseriti nei centri urbani</li>
<li><strong>gli alberi ad alto fusto inseriti in particolari complessi architettonici</strong> di importanza storica e culturale, quali ad esempio <strong>ville</strong>, monasteri, chiese, <strong>orti botanici</strong> e <strong>residenze storiche private.</strong></li>
</ul>
<p>Eventualmente se si desidera approfondire la tematica, questa <a href="./damiani.html">pagina</a> riassume l’intervento curato del Dott. Giovani Damiani, chimico e biologo, all’occasione del seminario “ Giardini Storici: la tutela dopo il PNRR ”. Il dott. Damiani ha anche contribuito alla stesura delle “Linee guida e norme tecniche per il restauro dei giardini storici” già ampiamente citato. Le informazioni condivise dalla sua esperienza attrezzeranno adeguatamente il lettore per capire molte delle problematiche di fondo che si affronteranno.</p>
<p>Ad esempio, la pertinenza dell’intervento è stato valutato in funzione del rapporto delle superfici vegetali individuate a terra e di quelle “artificializzate”. Secondo le informazioni da soli questi parametri sono insufficienti a valutarne l’impatto ed il contributo ecologico su un ecosistema complesso. Sono da considerare per il suolo anche il suo intero spessore e le sue qualità agronomiche così come anche il volume, l’estensione e la densità complessiva della canopea.</p>
<p><strong>Per quanto riguarda la preservazione del suolo</strong>, edotti delle nozioni elementari presente nel riassunto, si può facilmente intuire perché la pavimentazione in prossimità delle radici dei ficus monumentali sia fortemente sconsigliata; <strong>intralcia i meccanismi di scambio</strong> tra habitat adiacenti. Ad esempio impedisce l’accumulo naturale di sostanza organica come le foglie autunnali che ricoprono il suolo e migliorano il terreno proteggendolo dagli sbalzi termici e contribuiscono allo sviluppo dei microrganismi quali funghi simbionti e micorrize. Il fenomeno è così flagrante che in alcuni giardini è espressamente vietato l’asportazione di sostanza organica dal terreno così mettere a nudo l’apparato radicale oppure severamente vietarne l’interramento eccessivo con terra vegetale, sono tutti interventi che possono provocare degli squilibri nella rizosfera tali da addirittura distruggere quel microcosmo delicato ed indispensabile per la salute dell’albero, all’immagine del microbiota dell’apparato digestivo dell’essere umano.</p>
<p>Ora possiamo capire perchè persino la premura di utilizzare un vespaio areato (sistema tipo cupolex) per proteggere le radici dell’albero dalle sollecitazioni dovuto al calpestio non controbilancia tutte le contro indicazioni succitate. Anzi se consideriamo il caso straordinario in cui avvenisse per ipotesi una mareggiata: l’acqua salata del mare inonderebbe l’intercapedine d’aria inizialmente sistemata per garantire l’aerazione in tempi normali, in queste precise condizioni eccezionali quanto tempo ci vorrebbe perché le condizioni le condizioni tornassero alla normale in uno spazio confinato.</p>
<p>Tra l’altro questa sistemazione di una pavimentazione rialzata andrebbe a ridurre ancora di più l’altezza libera sotto i rami di questi alberi monumentali già bassi e restrittivi per quanto riguarda l’attività da svolgersi sotto.</p>
<p><strong>Per quanto riguarda la canopea</strong>, è la parte più attiva e per noi umani quella più preziosa, sede della fotosintesi, converte il minaccioso diossido di carbonio in ossigeno. Questo processo chimico è fortemente endotermico, l’evaporazione acquea contribuisce al raffrescamento come se fossero operativi dai 5 ai 10 condizionatori d’aria per 20 ore al giorno, senza consumo elettrico. Si può capire l’importanza di questo dato, quanto sia di vitale importanza nel momento in cui si pianifica il taglio, lo spostamento o la potatura dell’intera chioma di un albero! Ne subiscono le gravi conseguenze anche gli alberi vicini rimasti intatti; la zona d’intervento conosce inevitabilmente un aumento di temperatura media. Il fenomeno appare innocuo ma l’efficacia della conversione garantita dalla fotosintesi diminuisce fortemente con l’aumentare della temperatura media circostante, il processo benefico di conversione s’indebolisce, meno fotosintesi, meno evaporazione e a sua volta nuovo aumento di temperature, sono i temuti cicli di feedback positivi nella dinamica dei sistemi, più comunamente chiamati circoli viziosi. Ecco spiegato rapidamente uno dei motivi soggiacente <strong>al favorire l’aggregazione del verde pubblico: diventa più resiliente al riscaldamento climatico</strong> e sicuramente più piacevole per la cittadinanza.</p>
<p>Alla luce di quanto appena trattato e dall’osservazione della raccolta di fotografie satellitare che ritraccia sommariamente l’evoluzione della canopea della Villa Comunale dal 2010 ad oggi, si osserva una netta diminuzione della stessa, che sia per inasprimento del clima o per manutenzioni inadeguata, o del tutto assente, come più volte specificato da diverse parti, la situazione è purtroppo questa. Ora la domanda è: la riqualificazione proposta rimedia o rinforza questa tendenza?</p>
<p><strong>Per quanto riguarda l’aspetto botanico</strong>, la rimozione di alberature circostante porterebbe come altro effetto negativo la forte probabilità che i ficus andassero ad occupare lo spazio “vitale” adesso liberato, estendendo ancora di più i loro rami verso mare o il sole. La chioma mostra già una disimmetria accentuata verso sud. Un estensione maggiore in quella direzione potrebbe esercitare sul tronco, per effetto leva, sforzi tali da deteriorarlo. Oltretutto l’allargamento della chioma ricoprirebbe maggiormente l’area che il progetto prevede di riservare alla <em>scena</em> centrale quando l’altezza disponibile sotto i rami ne limita già la fruizione prima dei lavori. Bisogna tenere conto che quei alberi sono dei ficus tipo magnolioide, alberi sempreverde tra quelli più grandi tra i alberi di fico coltivati, crescono da 22 a 55 metri in altezza e da 21 a 40 metri in larghezza, a ragione di 90 cm in media l’anno, fino ad una venerabile età di 150 anni.</p>
<p><strong>A parere del comitato</strong>, per tutti i motivi sopracitati in un ambito <strong>di restauro del verde pubblico</strong>, così come viene classificato l’intervento nella scheda riassuntiva della proposta finanziata, <strong>le alberature avrebbero dovute essere rispristinate</strong>. Sulla pagina “<a href="./VCgeniusloci.html">Villa Comunale: Genius Loci</a>” sono raccolte delle imagine che ritracciano le trasformazioni apportate al sito. Se erano emerse, a suo tempo, delle valide motivazioni per rimuoverle, era indispensabile oggi individuarne la sussistenza di dette cause, e possibilmente rimediandone oggi le origini per preservare la salute avvenire della Villa. Immaginiamo che il taglio fosse stato reso necessario a causa di patologie o altri impedimenti, queste informazioni costituivano già una base di studio di notevole importanza per assestare o trattare l’ambiente perché potesse finalmente offrire delle condizioni di sviluppo migliori alle parte superstite.</p>
<p>Per tutti questi motivi, il comitato valuta molto negativamente la pavimentazione nei pressi degli alberi monumentali e suggerisce fortemente che non venga eseguita lasciando libera la superficie corrispondente all’estensione delle chiome soprastante.</p>
<p>Per sostenere ulteriormente le nostre tesi, il comitato ha individuato alcuni punti essenziali estrapolati dalle <strong>Linee guida per la gestione del verde urbano e prime indicazioni per una pianificazione sostenibile,</strong> per ognuno di essi sono evidenziati alcuni motivi, secondo il nostro umile parere, per i quali andrebbe rivisitata la proposta progettuale, ben inteso nel limite del possibile, oppure mettere i suggerimenti a dimora per i prossimi interventi.</p>
<p>I criteri di realizzazione di aree verdi ritenuti più attinente alla presente vicenda sono:</p>
<ul>
<li>priorità <strong>inserimento</strong> nel sistema del verde urbano esistente
<ul>
<li><span style="color:red;">La morfologia del verde urbano esistente, dalla raccolta delle fotografie satellitare degli anni precedenti, è stata profondamente alterata dalla compenetrazione urbana realizzata, gli alberi che componevano il filare frontistante agli alberi monumentali erano stati tagliati persino persino prima del rilievo e sostituti da quelli progettati a ridosso della tribuna nord allontanandoli dalla loro posizione originale all’interno della Villa Comunale.</span></li>
</ul></li>
<li>Massimizzare <strong>accorpamento</strong> per evitare frammentazioni e collocazione residuali
<ul>
<li><span style="color:red;">L’aggiunta della vegetazione è stata realizzata principalmente ad isola, distanziate dal fulcro vegetale originario in periferia</span></li>
</ul></li>
<li>Usi materiali ecocompatibile e <strong>riciclati e riciclabile</strong> che possono essere facilmente demoliti e riutilizzati o riciclati al termine dell’uso,
<ul>
<li><span style="color:red;">Il cemento armato utilizzato per la costruzione delle tribune non rientra in questa descrizione soprattutto nella fase di remissione, infatti all’inizio del cantiere è stata difficoltosa la rimozione dei blocchi di cemento inseriti dai pregressi interventi, sono dovuti intervenire di grossa potenza col rischio di creare una eccessiva compattazione dele terreno vegetale.</span></li>
</ul></li>
<li><strong>Biodiversità</strong>; composizioni vegetali miste rispetto a quelle in purezza, utilizzando specie che permettano l’alimentazione e il rifugio per insetti, uccelli e piccoli mammiferi e dell’avifauna
<ul>
<li><span style="color:red;">Sono stati previsti d’inseriti solamente le classiche palme, sarebbe stato auspicabile aggiungere essenze aromatiche per allontanare insetti attratti dalla futura illuminazione per la comodità degli spettatori</span></li>
</ul></li>
<li>Gestione acque pluviali (vasche, bacini di ritenzione, fossati inondabili)
<ul>
<li><span style="color:red;">Il dimensionamento dell’impianto di recupero dell’acque piovane è stato dimensionato solamente per garantire la gestione delle piogge “di intensità fino a mm 7 che equivale al valore medio nei peridi estivi per la città di Siderno. Superati questi valori limite le acque piovane in esubero verranno smaltite tramite rete comunale delle acque di raccolta pubbliche” (p.7 tav 01.1- Relazione specialistica dei sottosistemi a rete). Quando normalmente il sistema di recupero con le vasche di accumulo andrebbe dimensionato in funzione delle precipitazioni annue, in particolare di quelle più intense, proprio per poterle ridistribuire nei momenti più arridi.</span></li>
</ul></li>
<li><strong>Gestione suoli</strong>: preservare la fertilità del suolo adottando tutte gli accorgimenti per conservare e migliorare le caratteristiche chimiche, fisiche e la componente biologica del terreno;
<ul>
<li><strong>analisi del terreno,</strong>
<ul>
<li><span style="color:red;">risulta mancante qualsiasi analisi del terreno in merito alle caratteristiche su elencate</span></li>
</ul></li>
<li><strong>gestione movimenti e accantonamento dei primi strati vegetali del terreno,</strong>
<ul>
<li><span style="color:red;">sono assenti indicazioni specifiche sulla gestione dei primi strati vegetali del terreno</span></li>
</ul></li>
</ul></li>
<li><strong>Rilievo in scala adeguata di tutti gli elementi biotici ed abiotici</strong>
<ul>
<li><span style="color:red;">Sono stati rappresentati in pianta solamente gli alberi monumentali escludendo il resto della vegetazione arborea e arbustiva</span></li>
</ul></li>
<li><strong>Tabella con il calcolo della superficie di copertura arborea, arbustiva e erbacea</strong>. Oltre a questo sarà necessario elaborare una stima della copertura arborea a 25 anni dal collaudo.
<ul>
<li><span style="color:red;">Dagli elaborati pubblicati all’albo pretorio non risultano rilevati o indicati questi dati</span></li>
</ul></li>
<li><strong>Calcolo del fabbisogno idrico annuale stimato</strong>
<ul>
<li><span style="color:red;">Mancando i dati precedenti, il fabbisogno non può essere determinato con sufficiente precisione, era anche un dato necessario per il dimensionamento dell’impianto di recupero delle acque piovane citato prima.</span></li>
</ul></li>
</ul>
<p>Il comitato pensa che sono valutazioni fondate su ragionamenti e dati slegati dall’apprezzamento estetico, e quindi del tutto obbiettivi, che trovano fondatezza nel quadro normativo imposto dal principio cardine <strong>“di non recare danni significativi”</strong> all’ambiente. Ed è per questo motivo che s’invita la pubblica amministrazione a valutarle attentamente le proposte di variante e trarne gli aspetti migliori, nell’interesse della Villa Comunale e della cittadinanza. <strong>La riqualificazione va fatta al meglio delle risorse disponibili, finanziarie, materiali ed intellettuali.</strong></p>
</section>
<section id="ammissibilita-di-proposte-di-variante-in-corso-dopera" class="level2">
<h2 class="anchored" data-anchor-id="ammissibilita-di-proposte-di-variante-in-corso-dopera"><strong>AMMISSIBILITA DI PROPOSTE DI VARIANTE IN CORSO D’OPERA</strong></h2>
<p>Diverse volte ci è stato ripetuto l’impossibilità di travolgere un progetto di opere pubbliche approvato e finanziato, tuttavia in passato in alcuni casi di forza maggiore hanno testimoniato l’accoglimento di richieste di variante in corso d’opera, nel momento fossero riuniti determinati requisiti:</p>
<ul>
<li>Cantieristico: non comportino un aumento significativo dei costi (15%) o un allungamento eccessivo dei tempi di esecuzione dell’opera</li>
<li>Motivazione: Le varianti devono essere giustificate da ragioni tecniche, economiche o di pubblico interesse.</li>
<li>Conformità normativa: Le varianti non devono contravvenire alle normative vigenti, comprese quelle in materia di sicurezza, di tutela ambientale e di diritti dei lavoratori.</li>
<li>Concorrenza: Le varianti devono essere oggetto di una valutazione comparativa tra le diverse proposte e non devono alterare in maniera sostanziale i termini della gara d’appalto.</li>
<li>Autorizzazione: Le varianti devono essere approvate dall’ente appaltante e, se necessario, autorizzate dagli organi competenti.</li>
</ul>
</section>
<section id="analisi-dei-costi" class="level2">
<h2 class="anchored" data-anchor-id="analisi-dei-costi"><strong>ANALISI DEI COSTI</strong></h2>
<p>Nel caso fossero state accettate delle proposte di variante, era necessario individuarne il costo con l’analisi del computo metrico stesso allegato al progetto. Sono state esaminate rapidamente le voci che lo compongono così come quelle dell’elenco prezzi o dell’analisi dei prezzi e del prezzario regionale della regione Calabria 2023, le spese si ripartiscono mediamente così:</p>
<table>
<tbody>
<tr>
<th>
<ul>
<li>
opere paesaggistiche (€ 61.000)
</li>
<li>
arredi (€ 52.000)
</li>
</ul>
</th>
<th>
<ul>
<li>
pavimentazione (€ 325.669)
</li>
<li>
parcheggio (€ 295.791)
</li>
<li>
tribune (€ 221.225)
</li>
<li>
illuminazione (€ 236.792)
</li>
</ul>
</th>
</tr>
</tbody>
</table>
<p>Il grafico illustra di maniera più immediata la ripartizione dei costi:</p>
<p><img src="./assets/chart/costi.png" class="img-fluid"></p>
<p>Invece dalla documentazione riguardo il contratto di appalto è riportato a p.3 la percentuale approssimativa dei lavori per categoria, una disparità considerevole confermata dalle percentuali documentate:</p>
<p><img src="./assets/chart/percentuali.jpg" class="img-fluid"></p>
<p>dal quale emerge accessoriamente che circa solo il 9% delle somme erogate sono dedicate alle opere paesaggistiche (€ 61.000) e arredi (€ 52.000) mentre il restante 91 % alle opere “artificiali”,</p>
<p>Se chiedere un percentuale maggiore per le spese dedicate al verde sarebbe anche legittimo, rimane pur sempre più realistico richiedere quantomeno che lo sviluppo della parte minerale non pregiudichi minimamente su quella parte vegetativa.</p>
<p>Comunque nel caso in cui accogliate le nostre richieste valutandone i benefici sul lungo termine, accessoriamente per recuperare margini di manovra è stato reperito <strong>un esubero di spese di circa €130.000,00</strong> in sole due voci, è nel caso non fossero sufficienti, sono stati identificati, prima che fossero gettate le tribune, altre proposte di varianti che potessero allo stesso tempo diminuire alcune voci di spese migliorando anche l’impronta ecologica complessiva del progetto, di seguito una <strong>raccolta veloce di suggerimenti emessi durante i vari incontri del comitato</strong>:</p>
<section id="le-tribune" class="level3">
<h3 class="anchored" data-anchor-id="le-tribune"><strong>LE TRIBUNE</strong></h3>
<p>Per quanto riguarda la Tribuna Nord, si pensa che le dimensioni potevano essere più contenute, con un raggio minore, un’apertura più ristretta e una gradinata in meno, grazie ai dislivelli che presentava il sito, un integrazione maggiore poteva essere raggiunta. Le alternative a realizzarle piene e monolitiche col cemento armato erano numerose! Vero che ci è stato specificato che il cemento gettato è “green” – tale da dimezzare l’emissione di diossido di carbonio – ma in un contesto naturalistico, materiali sostitutivi di minore impatto ecologico e di più semplice rimozione a fine ciclo sono decisamente tanti, a cominciare dalle semplici gabbionate, per altro già adoperate per il ripristino del lungomare anni addietro, con qualche sapiente accorgimento possono acquistare eleganza quanto basta per discostarsi dalla semantica delle opere di contenimento stradali, cosa che stenta a compiere la scarna tribuna in cemento. In più, nella relazione tecnica si è insistito così tanto sull’idea di unificare gli spazi, il mare e la montagna, prevedendo persino di eliminare il dislivello della carreggiata. Poi da un tratto per quasi la totalità della lunghezza della zona d’intervento si erigono queste tribune per un altezza media di 2.00 m. Come possono persone di altezza media normale (1.80 m) percepire gli spazi dall’altra parte. Per questo scopo l’antica ringhiera in ferro battuto montata sul muretto non più alto del ginocchio aveva maggiore pertinenza.</p>
</section>
<section id="limpianto-di-illuminazione" class="level3">
<h3 class="anchored" data-anchor-id="limpianto-di-illuminazione"><strong>L’IMPIANTO DI ILLUMINAZIONE</strong></h3>
<p>Sicuramente l’impianto d’illuminazione verifica tutti i parametri per la comodità e la sicurezza dei futuri utenti, le schede sul funzionamento delle apparecchiature è dettagliatissima, mancano però le valutazioni riguardo gli effetti e le alterazioni del fotoperiodo che influenza notevolmente lo sviluppo delle piante, i ritmi circadiani dalla fauna e dei cittadini.</p>
<p>È da valutare l’utilità effettiva delle due torri di luce previste in origine per illuminare dall’alto la scena centrale dell’anfiteatro essendo in gran parte coperta dalle chiome degli alberi monumentali centrali che ostacolerebbero la luce proiettata.</p>
</section>
<section id="limpianto-dirrigazione" class="level3">
<h3 class="anchored" data-anchor-id="limpianto-dirrigazione"><strong>L’IMPIANTO D’IRRIGAZIONE</strong></h3>
<p>Sono stati suggeriti - l’uso di un sistema d’irrigazione a gocce, - un sistema di nebulizzazione, - delle fontane funzionante, per quanto riguarda la gestione del recupero delle acque sono già stati precedentemente espressi i dubbi sulla capacità dell’impianto progettato con le caratteristiche descritte nella relazione specialistica ad assolvere il suo compito nel modo più efficace.</p>
</section>
<section id="limpianto-di-diffusione-acustica" class="level3">
<h3 class="anchored" data-anchor-id="limpianto-di-diffusione-acustica"><strong>L’IMPIANTO DI DIFFUSIONE ACUSTICA</strong></h3>
<p>L’utenza, come comunità è già inondata da flussi di dati e informazione continui, ci si chiede se non fosse il caso di riservare un’oasi di prossimità dove i cittadini possono estraniarsi momentaneamente. Un posto dove sottrarsi a quello che oggi viene denominato come <strong>infotossicazione</strong>. Quale ambiente migliore della Villa Comunale, dove un panorama sonoro naturale garantirebbe questa evasione temporanea grazie ad un ecosistema vegetativo naturale vivo, vero e sano (insetti, avifauna, vento nelle foglie, rumore del mare possibilmente privi del rombo dei veicoli), sperando che non capiti mai una “primavera silenziosa” senza l’ausilio di surrogati digitali quando abbiamo la possibilità di avere concretamente il luogo adatto.</p>
</section>
</section>
<section id="i-chiarimenti" class="level2">
<h2 class="anchored" data-anchor-id="i-chiarimenti"><strong>I CHIARIMENTI</strong></h2>
<p>È stata portata a conoscenza del comitato che:</p>
<ul>
<li><ul>
<li>Il comitato comunicava che la riqualificazione comportava la diminuzione del 42% di superficie vegetativa sulla base della tavola 7.3 Superficie permeabili durante l’evento del 24 maggio 2024 tenutasi all’YMCA. il R.U.P. l’Ing. Surace ha rimarcato che sono state identifica più dettagliatamente le reali superfici, per natura ed estensione specifiche, nella tavola 7.2.8 non ancora pubblicata al momento dell’incontro. Dal rilievo risulterebbe allora un’estensione ante operam del tappetto vegetale di molto inferiore a quanto indicato nella tavola 7.3. A lavori compiuti come da progetto dovrebbe esserci addirittura un aumento della superficie vegetale finale.</li>
</ul></li>
<li>Sono stati individuati e repertoriati gli alberi monumentali perché godano di tutte le misure di salvaguardia disposte per leggi, e che gli altri esemplari ad alto fusto sono stati trapiantati ove necessario con tutte le dovute cure,</li>
<li>il cemento adoperato è un cemento rispettoso dell’ambiente in quanto il suo utilizzo emette il 50% in meno di diossido di carbonio e che non sono stati introdotti quantitativi aggiuntivi a quelli rimossi dagli interventi pregressi, al contrario.</li>
<li>che la pavimentazione utilizzata è fortemente drenante per permettere alle acque di percolare nel terreno soggiacente o di essere raccolte nelle apposite vasche di accumulo.</li>
</ul>
<p>Il comitato “sasso nello stagno” ha poi rimarcato che:</p>
<ul>
<li>Dato che la tavola sarà messa a disposizione per studiarla, ci si riserva di rispondere una volta esaminata con cura. [comunque dal rilievo fotografico le uniche superfici non inverdite sono le rampe e le scale in cemento così come le aere destinate al transito pedonale ricoperte di ghiaia]</li>
<li>il rilevamento degli alberi monumentali esistenti è sicuramente un’ottima iniziativa, ma che andrebbe integrata con le disposizioni dell’art.7 della L 10/2013 che estende la monumentalità a tutti gli alberi che compongono la vegetazione arborea della villa,</li>
<li>il cemento più ecologico è quello che non si usa e che c’erano sicuramente soluzioni costruttive che potevano ridurne considerevolmente l’impiego assecondando maggiormente gli obbiettivi fissati dai Criteri Ambientali Minimi (C.A.M.).</li>
<li>Seppure la pavimentazione drenante può presentare delle permeabilità migliore dei terreni naturali, non possiede sicuramente lo stesso potenziale biologico e costituisce invariabilmente uno strato di isolamento riguardo alcuni processi di scambio (ossigeno, nutrienti, concimi, etc… ) tra habitat contigui soprattutto in prossimità degli apparati radicali appartenenti ai ficus centrali</li>
</ul>
</section>
<section id="rassegna-stampa" class="level1">
<h1><strong>RASSEGNA STAMPA</strong></h1>
<ul>
<li><p><a href="https://www.radiocrt.it/podcast2/massimiliano-capalbo-quando-i-finanziamenti-fanno-male-al-verde/">Massimiliano Capalbo – Quando i finanziamenti fanno male al verde.</a></p></li>
<li><p><a href="https://www.rivieraweb.it/lo-scellerato-anfiteatro-della-villa-di-siderno-marina/">Lo scellerato anfiteatro della villa di Siderno marina</a></p></li>
<li><p><a href="https://www.incipitsistemacomunicazione.it/2024/03/26/%f0%9d%90%82%f0%9d%90%8e%f0%9d%90%8d%f0%9d%90%93%f0%9d%90%91%f0%9d%90%8e-%f0%9d%90%88%f0%9d%90%8b-%f0%9d%90%82%f0%9d%90%84%f0%9d%90%8c%f0%9d%90%84%f0%9d%90%8d%f0%9d%90%93%f0%9d%90%8e-%f0%9d%90%8d/">𝐂𝐎𝐍𝐓𝐑𝐎 𝐈𝐋 𝐂𝐄𝐌𝐄𝐍𝐓𝐎 𝐍𝐄𝐋𝐋𝐀 𝐕𝐈𝐋𝐋𝐀 𝐒𝐔𝐋 𝐋𝐔𝐍𝐆𝐎𝐌𝐀𝐑𝐄 𝐃𝐈 𝐒𝐈𝐃𝐄𝐑𝐍𝐎 𝐍𝐔𝐎𝐕𝐎 𝐈𝐍𝐂𝐎𝐍𝐓𝐑𝐎 𝐈𝐋 𝐍𝐎𝐕𝐄 𝐀𝐏𝐑𝐈𝐋𝐄</a></p></li>
<li><p><a href="https://www.ecodellalocride.it/news/siderno-antonella-avellis-sui-lavori-di-riqualificazione-della-storica-villa-comunale/">Siderno: Antonella Avellis sui lavori di riqualificazione della storica Villa Comunale</a></p></li>
<li><p><a href="https://www.rivieraweb.it/siderno-comitato-un-sasso-nello-stagno-svolto-incontro-sulla-villa-comunale/">Siderno, comitato “Un sasso nello stagno”: svolto incontro sulla Villa Comunale</a></p></li>
<li><p><a href="./assets/rassegna/La villa comunale stroncata anche dal circolo meloniano.jpeg">La villa comunale stroncata dal circolo meloniano</a></p></li>
</ul>
</section>
<section id="rissorse-esterne" class="level1">
<h1><strong>RISSORSE ESTERNE</strong></h1>
<ul>
<li>La documentazione ufficiale del progetto può essere scaricata dal seguente <a href="https://siderno-api.municipiumapp.it/s3/6888/allegati/progetto-villa-per-albo-trasparenza.zip">link</a></li>
<li><a href="https://www.mase.gov.it/sites/default/files/archivio/normativa/legge_14_01_2013_10.pdf">LEGGE 14 gennaio 2013 , n.&nbsp;10</a> Norme per lo sviluppo degli spazi verdi urbani</li>
<li><a href="https://www.mase.gov.it/sites/default/files/archivio/allegati/comitato%20verde%20pubblico/lineeguida_finale_25_maggio_17.pdf">Linee guida</a> per la <strong>gestione del verde urbano</strong> e prime indicazioni per una <strong>pianificazione sostenibile</strong></li>
<li><a href="https://www.apgi.it/wp-content/uploads/2022/01/SCARICA-LE-LINEE-GUIDA-E-NORME-TECNICHE-PER-IL-RESTAURO-DEI-GIARDINI-STORICI.pdf">Linee guida e norme tecniche</a> per il <strong>Restauro dei Giardini Storici</strong></li>
<li><a href="https://www.consiglioregionale.calabria.it/bdf/api/BDF?numero=7&amp;anno=2024">legge regionale del 07 febbraio 2024</a> riguardo le Norme in materia di <strong>valorizzazione delle aree verdi</strong> e delle formazioni vegetali in ambito urbano.</li>
<li></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/unsassonellostagno\.github\.io\/usns\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>