---
title: "LA PERTINENZA DEL PROGETTO"

---

Ad esempio, la pertinenza dell'intervento è stato valutato in funzione del rapporto delle superfici vegetali individuate a terra e di quelle "artificializzate". Secondo le informazioni  da soli questi parametri sono insufficienti a valutarne l'impatto ed il contributo ecologico su un ecosistema complesso. Sono da considerare per il suolo anche il suo intero spessore e le sue qualità agronomiche così come anche il volume, l'estensione e la densità complessiva della canopea.

**Per quanto riguarda la preservazione del suolo**, edotti delle nozioni elementari presente nel riassunto, si può facilmente intuire perché la pavimentazione in prossimità delle radici dei ficus monumentali sia fortemente sconsigliata; **intralcia i meccanismi di scambio** tra habitat adiacenti. Ad esempio impedisce l’accumulo naturale di sostanza organica come le foglie autunnali che ricoprono il suolo e migliorano il terreno proteggendolo dagli sbalzi termici e contribuiscono allo sviluppo dei microrganismi quali funghi simbionti e micorrize. Il fenomeno è così flagrante che in alcuni giardini è espressamente vietato l’asportazione di sostanza organica dal terreno così mettere a nudo l’apparato radicale oppure severamente vietarne l’interramento eccessivo con terra vegetale, sono tutti interventi che possono provocare degli squilibri nella rizosfera tali da addirittura distruggere quel microcosmo delicato ed indispensabile per la salute dell'albero, all'immagine del microbiota dell'apparato digestivo dell'essere umano.

Ora possiamo capire perché persino la premura di utilizzare un vespaio areato (sistema tipo cupolex) per proteggere le radici dell'albero dalle sollecitazioni dovuto al calpestio non controbilancia tutte le contro indicazioni succitate. Anzi se consideriamo il caso straordinario in cui avvenisse per ipotesi una mareggiata: l’acqua salata del mare inonderebbe l’intercapedine d’aria inizialmente sistemata per garantire l’aerazione in tempi normali, in queste precise condizioni eccezionali quanto tempo ci vorrebbe perché le condizioni le condizioni tornassero alla normale in uno spazio confinato.

Tra l’altro questa sistemazione di una pavimentazione rialzata andrebbe a ridurre ancora di più l’altezza libera sotto i rami di questi alberi monumentali già bassi e restrittivi per quanto riguarda l'attività da svolgersi sotto.

**Per quanto riguarda la canopea**, è la parte più attiva e per noi umani quella più preziosa, sede della fotosintesi, converte il minaccioso diossido di carbonio in ossigeno. Questo processo chimico è fortemente endotermico, l’evaporazione acquea contribuisce al raffrescamento come se fossero operativi dai 5 ai 10 condizionatori d’aria per 20 ore al giorno, senza consumo elettrico. Si può capire l'importanza di questo dato, quanto sia di vitale importanza nel momento in cui si pianifica il taglio, lo spostamento o la potatura dell'intera chioma di un albero! Ne subiscono le gravi conseguenze anche gli alberi vicini rimasti intatti; la zona d'intervento conosce inevitabilmente un aumento di temperatura media. Il fenomeno appare innocuo ma l'efficacia della conversione garantita dalla fotosintesi diminuisce fortemente con l’aumentare della temperatura media circostante, il processo benefico di conversione s’indebolisce, meno fotosintesi, meno evaporazione e a sua volta nuovo aumento di temperature, sono i temuti cicli di feedback positivi nella dinamica dei sistemi, più comunamente chiamati circoli viziosi. Ecco spiegato rapidamente uno dei motivi soggiacente **al favorire l’aggregazione del verde pubblico: diventa più resiliente al riscaldamento climatico** e sicuramente più piacevole per la cittadinanza.

Alla luce di quanto appena trattato e dall’osservazione della raccolta di fotografie satellitare che ritraccia sommariamente l’evoluzione della canopea della Villa Comunale dal 2010 ad oggi, si osserva una netta diminuzione della stessa, che sia per inasprimento del clima o per manutenzioni inadeguata, o del tutto assente, come più volte specificato da diverse parti, la situazione è purtroppo questa. Ora la domanda è: la riqualificazione proposta rimedia o rinforza questa tendenza?

**Per quanto riguarda l’aspetto botanico**, la rimozione di alberature circostante porterebbe come altro effetto negativo la forte probabilità che i ficus andassero ad occupare lo spazio “vitale” adesso liberato, estendendo ancora di più i loro rami verso mare o il sole. La chioma mostra già una disimmetria accentuata verso sud. Un estensione maggiore in quella direzione potrebbe esercitare sul tronco, per effetto leva, sforzi tali da deteriorarlo.  Oltretutto l’allargamento della chioma ricoprirebbe maggiormente l’area che il progetto prevede di riservare alla *scena* centrale quando l’altezza disponibile sotto i rami ne limita già la fruizione prima dei lavori. 
Bisogna tenere conto che quei alberi sono dei ficus tipo magnolioide, alberi sempreverde tra quelli più grandi tra i alberi di fico coltivati, crescono da 22 a 55 metri in altezza e da 21 a 40 metri in larghezza, a ragione di 90 cm in media l’anno, fino ad una venerabile età di 150 anni.

**A parere del comitato**, per tutti i motivi sopracitati in un ambito **di restauro del verde pubblico**, così come viene classificato l’intervento nella scheda riassuntiva della proposta finanziata, **[le alberature avrebbero dovute essere rispristinate](areeverdi.qmd)**. Sulla pagina [Villa Comunale: Genius Loci](gloci.qmd) sono raccolte delle imagine che ritracciano le trasformazioni apportate al sito.
Se erano emerse, a suo tempo, delle valide motivazioni per rimuoverle, era indispensabile oggi individuarne la sussistenza di dette cause, e possibilmente rimediandone oggi le origini per preservare la salute avvenire della Villa. Immaginiamo che il taglio fosse stato reso necessario a causa di patologie o altri impedimenti, queste informazioni costituivano già una base di studio di notevole importanza per assestare o trattare l’ambiente perché potesse finalmente offrire delle condizioni di sviluppo migliori alle parte superstite. 

Per tutti questi motivi, il comitato valuta molto negativamente la pavimentazione nei pressi degli alberi monumentali e suggerisce fortemente che non venga eseguita lasciando libera la superficie corrispondente all’estensione delle chiome soprastante.

Per sostenere ulteriormente le nostre tesi, il comitato ha individuato alcuni punti essenziali estrapolati dalle **Linee guida per la gestione del verde urbano e prime indicazioni per una pianificazione sostenibile,** per ognuno di essi sono evidenziati alcuni motivi, secondo il nostro umile parere, per i quali andrebbe rivisitata la proposta progettuale, ben inteso nel limite del possibile, oppure mettere i suggerimenti a dimora per i prossimi interventi.

I criteri di realizzazione di aree verdi ritenuti più attinente alla presente vicenda sono:

- priorità **inserimento** nel sistema del verde urbano esistente
  -  <span style="color:red;">La morfologia del verde urbano esistente, dalla raccolta delle fotografie satellitare degli anni precedenti, è stata profondamente alterata dalla compenetrazione urbana realizzata, gli alberi che componevano il filare frontistante agli alberi monumentali erano stati tagliati persino persino prima del rilievo e sostituti da quelli progettati a ridosso della tribuna nord allontanandoli dalla loro posizione originale all’interno della Villa Comunale.</span>
- Massimizzare **accorpamento** per evitare frammentazioni e collocazione residuali
  - <span style="color:red;">L’aggiunta della vegetazione è stata realizzata principalmente ad isola, distanziate dal fulcro vegetale originario in periferia
- Usi materiali ecocompatibile e **riciclati e riciclabile** che possono essere facilmente demoliti e riutilizzati o riciclati al termine dell’uso,</span>
  - <span style="color:red;">Il cemento armato utilizzato per la costruzione delle tribune non rientra in questa descrizione soprattutto nella fase di remissione, infatti all’inizio del cantiere è stata difficoltosa la rimozione dei blocchi di cemento inseriti dai pregressi interventi, sono dovuti intervenire di grossa potenza col rischio di creare una eccessiva compattazione dele terreno vegetale.</span>
- **Biodiversità**; composizioni vegetali miste rispetto a quelle in purezza, utilizzando specie che permettano l’alimentazione e il rifugio per insetti, uccelli e piccoli mammiferi e dell’avifauna
  - <span style="color:red;">Sono stati previsti d’inseriti solamente le classiche palme, sarebbe stato auspicabile aggiungere essenze aromatiche per allontanare insetti attratti dalla futura illuminazione per la comodità degli spettatori</span>
- Gestione acque pluviali (vasche, bacini di ritenzione, fossati inondabili)
  - <span style="color:red;">Il dimensionamento dell’impianto di recupero dell’acque piovane è stato dimensionato solamente per garantire la gestione delle piogge “di intensità fino a mm 7 che equivale al valore medio nei peridi estivi per la città di Siderno. Superati questi valori limite le acque piovane in esubero verranno smaltite tramite rete comunale delle acque di raccolta pubbliche” (p.7 tav 01.1- Relazione specialistica dei sottosistemi a rete). Quando normalmente il sistema di recupero con le vasche di accumulo andrebbe dimensionato in funzione delle precipitazioni annue, in particolare di quelle più intense, proprio per poterle ridistribuire nei momenti più arridi.</span>
- **Gestione suoli**: preservare la fertilità del suolo adottando tutte gli accorgimenti per conservare e migliorare le caratteristiche chimiche, fisiche e la componente biologica del terreno;
  - **analisi del terreno,**
    - <span style="color:red;">risulta mancante qualsiasi analisi del terreno in merito alle caratteristiche su elencate</span>
  - **gestione movimenti e accantonamento dei primi strati vegetali del terreno,**
    - <span style="color:red;">sono assenti indicazioni specifiche sulla gestione dei primi strati vegetali del terreno</span>
- **Rilievo in scala adeguata di tutti gli elementi biotici ed abiotici**
  - <span style="color:red;">Sono stati rappresentati in pianta solamente gli alberi monumentali escludendo il resto della vegetazione arborea e arbustiva</span>
- **Tabella con il calcolo della superficie di copertura arborea, arbustiva e erbacea**. Oltre a questo sarà necessario elaborare una stima della copertura arborea a 25 anni dal collaudo.
  - <span style="color:red;">Dagli elaborati pubblicati all’albo pretorio non risultano rilevati o indicati questi dati</span>
- **Calcolo del fabbisogno idrico annuale stimato**
  - <span style="color:red;">Mancando i dati precedenti, il fabbisogno non può essere determinato con sufficiente precisione, era anche un dato necessario per il dimensionamento dell’impianto di recupero delle acque piovane citato prima.</span>

Il comitato pensa che sono valutazioni fondate su ragionamenti e dati slegati dall’apprezzamento estetico, e quindi del tutto obbiettivi, che trovano fondatezza nel quadro normativo imposto dal principio cardine **“di non recare danni significativi”** all’ambiente. Ed è per questo motivo che s'invita la pubblica amministrazione a valutarle attentamente le proposte di variante e trarne gli aspetti migliori, nell’interesse della Villa Comunale e della cittadinanza. **La riqualificazione va fatta al meglio delle risorse disponibili, finanziarie, materiali ed intellettuali.**