---
title: "La Tutella del VERDE URBANO nell'ambito del PNRR"

---

Un'altra distinzione importante effettuata a monte fra i vari progetti finanziati sono quelli che mirano specificatamente ad una drastica riduzione d’emissione o di concentrazione del diossido di carbonio nell’atmosfera durante la loro fase di esercizio e quelli, simili a quello in oggetto, che **non la perseguono attivamente**. Per quest'ultimi vige Il **"regime 2".** molto più permissivo del regime 1. Tuttavia questo regime impone quantomeno il rispetto del principio di **“non arrecare danno significativo"** (Do Not Significantly Harm|DNSH) all’ambiente circostante. Tant'è vero che questo aspetto viene chiaramente richiamato dal progettista nella relazione tecnica a p.44 quando citta sia la L. N. 10/2013 “norme per lo sviluppo degli spazi verdi urbani” che le linee guide successivamente ufficializzate dal Ministero dell’Ambiente e della tutela del territorio e del mare nel 2017. Alcuni dei suoi concetti s’incrociano naturalmente con Linee guide dedicate specificamente ai Parchi e Giardini Storici citato precedentemente. Qui appresso si tenta di riassumerne alcuni tra i più significativi in relazione con le opere in itinere condotte presso la Villa Comunale di Siderno.

La tutela del Verde Urbano è quindi resa obbligatoria al momento dell’adesione al programma d’investimento. I principi cardini della pianificazione del verde sono riassunti con **l’art. 6** **L.10/2013 che prevede**:

1. **il rinverdimento** per le nuove costruzione e ristrutturazione edilizia significativa.
2. **L’incremento, la conservazione e la tutela del patrimonio arboreo** per gli edifici esistenti
3. La raccolta efficace delle acque piovane, **efficienza energetica**,
4. riduzione effetto isola di calore, formazione del personale addetto ai lavori,
5. sensibilizzazione della cittadinanza

mentre **l’art.7 estende l’applicazione delle prescrizioni non solo all’albero monumentale ma a tutte le alberature che rispondono ai seguenti criteri:**

- **alberi ad alto fusto singoli** in ambiente naturali o artificiali che presentano caratteristiche fisiche straordinarie oppure caratteristiche storiche culturale rilevanti
- **i filari o alberate di particolare pregio paesaggistico**, monumentale, storico e culturale, ivi compresi quelli inseriti nei centri urbani
- **gli alberi ad alto fusto inseriti in particolari complessi architettonici** di importanza storica e culturale, quali ad esempio **ville**, monasteri, chiese, **orti botanici** e **residenze storiche private.**

Eventualmente se si desidera approfondire la tematica, questa [pagina](damiani.qmd) riassume l'intervento curato del Dott. Giovani Damiani, chimico e biologo, all’occasione del seminario “ Giardini Storici: la tutela dopo il PNRR ”. Il dott. Damiani ha anche contribuito alla stesura delle “Linee guida e norme tecniche per il restauro dei giardini storici” già ampiamente citato. Le informazioni condivise dalla sua esperienza attrezzeranno adeguatamente il lettore per capire molte delle problematiche di fondo che si affronteranno.