---
title: "Le Proposte di Varianti"

---

AMMISSIBILITA DI PROPOSTE DI VARIANTE IN CORSO D'OPERA


Diverse volte ci è stato ripetuto l’impossibilità di travolgere un progetto di opere pubbliche approvato e finanziato, tuttavia in passato in alcuni casi di forza maggiore hanno testimoniato l’accoglimento di richieste di variante in corso d’opera, nel momento fossero riuniti determinati requisiti:

- Cantieristico: non comportino un aumento significativo dei costi (15%) o un allungamento eccessivo dei tempi di esecuzione dell'opera
- Motivazione: Le varianti devono essere giustificate da ragioni tecniche, economiche o di pubblico interesse.
- Conformità normativa: Le varianti non devono contravvenire alle normative vigenti, comprese quelle in materia di sicurezza, di tutela ambientale e di diritti dei lavoratori.
- Concorrenza: Le varianti devono essere oggetto di una valutazione comparativa tra le diverse proposte e non devono alterare in maniera sostanziale i termini della gara d'appalto.
- Autorizzazione: Le varianti devono essere approvate dall'ente appaltante e, se necessario, autorizzate dagli organi competenti.


### **LE TRIBUNE**

Per quanto riguarda la Tribuna Nord, si pensa che le dimensioni potevano essere più contenute, con un raggio minore, un’apertura più ristretta e una gradinata in meno, grazie ai dislivelli che presentava il sito, un integrazione maggiore poteva essere raggiunta. Le alternative a realizzarle piene e monolitiche col cemento armato erano numerose! Vero che ci è stato specificato che il cemento gettato è “green” – tale da dimezzare l’emissione di diossido di carbonio – ma in un contesto naturalistico, materiali sostitutivi di minore impatto ecologico e di più semplice rimozione a fine ciclo sono decisamente tanti, a cominciare dalle semplici gabbionate, per altro già adoperate per il ripristino del lungomare anni addietro, con qualche sapiente accorgimento possono acquistare eleganza quanto basta per discostarsi dalla semantica delle opere di contenimento stradali, cosa che stenta a compiere la scarna tribuna in cemento.
In più, nella relazione tecnica si è insistito così tanto sull'idea di unificare gli spazi, il mare e la montagna, prevedendo persino di eliminare il dislivello della carreggiata. Poi da un tratto per quasi la totalità della lunghezza della zona d'intervento si erigono queste tribune per un altezza media di 2.00 m. Come possono persone di altezza media normale (1.80 m) percepire gli spazi dall'altra parte. Per questo scopo l'antica ringhiera in ferro battuto montata sul muretto non più alto del ginocchio aveva maggiore pertinenza. 


### **L’IMPIANTO DI ILLUMINAZIONE**

Sicuramente l’impianto d’illuminazione verifica tutti i parametri per la comodità e la sicurezza dei futuri utenti, le schede sul funzionamento delle apparecchiature è dettagliatissima, mancano però le valutazioni riguardo gli effetti e le alterazioni del fotoperiodo che influenza notevolmente lo sviluppo delle piante, i ritmi circadiani dalla fauna e dei cittadini.

È da valutare l’utilità effettiva delle due torri di luce previste in origine per illuminare dall’alto la scena centrale dell’anfiteatro essendo in gran parte coperta dalle chiome degli alberi monumentali centrali che ostacolerebbero la luce proiettata.

Sarebbe preferibile di evitare qualsiasi scavo in prossimità delle radici per fare passare i vari impianti.

### **L’IMPIANTO D’IRRIGAZIONE**

Sono stati suggeriti 
- l’uso di un sistema d’irrigazione a gocce,
- un sistema di nebulizzazione, 
- delle fontane funzionante, 
per quanto riguarda la gestione del recupero delle acque sono già stati precedentemente espressi i dubbi sulla capacità dell'impianto progettato con le caratteristiche descritte nella relazione specialistica ad assolvere il suo compito nel modo più efficace.

### **L’IMPIANTO DI DIFFUSIONE ACUSTICA**

L’utenza, come comunità è già inondata da flussi di dati e informazione continui, ci si chiede se non fosse il caso di riservare un’oasi di prossimità dove i cittadini possono estraniarsi momentaneamente. Un posto dove sottrarsi a quello che oggi viene denominato come **infotossicazione**. Quale ambiente migliore della Villa Comunale, dove un panorama sonoro naturale garantirebbe questa evasione temporanea grazie ad un ecosistema vegetativo naturale vivo, vero e sano (insetti, avifauna, vento nelle foglie, rumore del mare possibilmente privi del rombo dei veicoli), sperando che non capiti mai una “primavera silenziosa” senza l’ausilio di surrogati digitali quando abbiamo la possibilità di avere concretamente il luogo adatto.