---
title: "il 5G"
date: 30 05 2024
date-modified: last-modified
---
E' lecito dare un piccolo riassunto su tutti i vantaggi e difetti riconosciuti a questa tecnologia senza entrare troppo in dettagli tecnologici.


**Pro della tecnologia 5G:**

- Velocità di Download e Upload: Il 5G offre velocità di download e upload significativamente superiori rispetto alle tecnologie precedenti (4G, 3G). Questo permette di scaricare file molto grandi in pochi secondi.
- Bassa Latenza: La latenza del 5G è molto bassa, il che significa che il tempo di risposta tra l'invio di un comando e la ricezione di una risposta è quasi istantaneo. Questo è particolarmente importante per applicazioni come i giochi online, la realtà virtuale e aumentata, e le operazioni a distanza (es. chirurgia robotica).
- Maggiore Capacità: Il 5G può supportare un numero molto maggiore di dispositivi connessi contemporaneamente senza perdere in prestazioni. Questo è cruciale con l'aumento dell'Internet delle Cose (IoT), dove molti dispositivi intelligenti sono collegati tra loro.
- Efficienza Energetica: Le reti 5G sono progettate per essere più efficienti dal punto di vista energetico rispetto alle reti precedenti, riducendo il consumo energetico per bit trasmesso.
- Nuove Opportunità: Il 5G apre la strada a nuove applicazioni e servizi che richiedono alte velocità di trasmissione dati e bassa latenza, come veicoli autonomi, smart cities e telemedicina.


**Contro della tecnologia 5G:**

- Costi Elevati: La costruzione dell'infrastruttura necessaria per il 5G è costosa. Le nuove antenne devono essere installate più densamente rispetto al 4G, aumentando i costi di implementazione.
- Copertura Limitata: Al momento, la copertura del 5G non è uniforme. Le aree rurali e meno densamente popolate possono rimanere senza copertura per più tempo rispetto alle aree urbane.
- Preoccupazioni sulla Salute: Ci sono alcune preoccupazioni riguardo agli effetti sulla salute delle frequenze radio utilizzate dal 5G, anche se finora non ci sono prove scientifiche definitive che dimostrino effetti negativi significativi.
- Interferenze: La banda millimetrica usata dal 5G può essere suscettibile alle interferenze da ostacoli fisici come edifici e alberi, e può essere influenzata dalle condizioni meteorologiche.
- Problemi di Sicurezza: Con l'aumento del numero di dispositivi connessi, la sicurezza diventa un problema più complesso. La rete 5G dovrà affrontare sfide significative per garantire che i dati e i dispositivi siano protetti da minacce informatiche.

I potenziali di questa tecnologia sono degni dei piu belli scenari fanta scientifici, riportano però alla dura realtà alcuni fatti non troppo sporadici come alcuni anni fà non erano per esempio disponibili anti tetaniche presso i pronti soccorso degli ospedali. Questa osservazione non viene mossa per criticare la tecnologia del 5G, ma è una parentesi piena di significato per evidenziare che prima di rincorrere la cometa del progresso inarrestabile sarebbe auspicabile riconoscere che il grano continua a necessitare di una anno intero a crescere ed essere raccolto, ovvero serve consolidare altri numerosi aspetti delle "infrastrutture" sociali prima di vedere ricadute significative dell'impiego delle nuove tecnologie. La dematerializzazione degli enti governativi era stata introdotta circa il 2006, ancora oggi siamo ben lontani di aver concluso il travaso analogico digitale e non è certo legato all'esistenza o meno del 5G.
L'adozione di queste tecnologie di tendenza non sono rimedi miracoli contro le patologie che investono il territorio Calabrese o Locrideo in particolare.


Per approfondimenti sull'incidenza dei campi elettromagnetici si può consultare il sito: [a2c](https://www.a2c.it/News-Campi-elettromagnetici/)