---
title: "Cantiere in Corso d'Opera"
---

Era stato evidenziato che una delle pecche del progetto erano le tribune che assomigliavano a delle opere di contenimento delle scarpate senza che ci fossero effettivamente delle scarpate da reggere.

la direzione dei Lavori sembra si sia risoluta a rimediare questo paradosso sistemando del terreno vegetale in pendenza a ridosso delle tribune nelle aiuole di nuova costruzione in modo da creare un piano erboso inclinato molto simile a quello gia presente di fronte l'ingresso principale della Casa Comunale.

La soluzione è lodevole in quanto nasconde la presenza delle massicciate in cemento armate dietro forme piu morbide all'occhio. Tuttavia dopo un attimo di riflessione, nasce spontanea la domanda  se sagomare preventivamente il sito con il terreno naturale non avrebbe permesso di sistemare le medesime sedute impiegando molto meno cemento ? 

Possibile che i Lidi estivi stagionali mostrano maggiore maturità preferendo sagomare la spiaggia per animare l'assetto altrimenti ritenuto monotono con la semplice movimentazione della sabbia all'uso ingombranti di manufatti cementizi, anche con notevole risparmio sull'utilizzo del materiale adoperato, quando invece, nel caso del "Restauro della Villa" il progetto prevede un notevole dispendio di risorse per ottenere [risultati da mitigare pesantemente dal punto di vista ambientale o naturalistico](inc_02_chia.qmd).