---
title: "le INTERRAZIONI"
---

## **IL CALENDARIO**


il 26 gennaio 2024. protocollata la prima istanza di accesso atti.

il 07 febbraio 2024, primo incontro col Sindaco, Dott.ssa Mariateresa Fragomeni, per comunicare le nostre prime riserve e perplessità sui lavori in corso

il 17 febbraio 2024, protocollata la seconda istanza accesso atti a rilancio del primo

il 23 Marzo 2024, [evento divulgativo](ymca.qmd) indirizzata a tutta la cittadinanza interessata organizzato presso i locali dell'YMCA in merito ai lavori in corso presso la Villa Comunale di Siderno.

il 09 aprile 2024, secondo incontro col Sindaco coadiuvata dagli assessori di ramo e del Dirigente dell'Ufficio dei Lavori Pubblici, Ing. L. Surace. Sono stati scambiati alcuni punti di vista significativi riportati in calce a questa pagina nella sezione chiarimenti.

il 09 maggio 2024 presentazione della terza istanza di accesso atti in complemento ai primi 2 per accedere a documentazione non ancora pubblicata

il 10 maggio 2024, l'Ufficio Tecnico ha finalmente inviato la documentazione


## **I CHIARIMENTI**

Nella riunione del 09 Aprile 2024, la Pubblica Amministrazione ha portato alla nostra attenzione i seguenti punti:

- In risposta all'affermazione comunicata dal comitato riguardo la diminuzione del 42% di superficie vegetativa sulla base della tavola 7.3 Superficie permeabili durante l’evento del 24 maggio 2024 tenutasi all’YMCA,  il R.U.P. l’Ing. Surace ha rimarcato che sono state identifica in seguito più dettagliatamente le reali superfici, per natura ed estensione specifiche, e sono state riportate nella tavola 7.2.8 non ancora pubblicata al momento dell’incontro ma ben presto messo a disposizione. Da questo nuovo elaborato risulterebbe allora un’estensione ante operam del tappetto vegetale di molto inferiore a quanto indicato nella tavola 7.3. Di conseguenza a lavori compiuti come da progetto dovrebbe esserci addirittura un aumento della superficie vegetale finale.
- Sono stati individuati e repertoriati gli alberi monumentali perché godano di tutte le misure di salvaguardia disposte per leggi, e che gli altri esemplari ad alto fusto sono stati trapiantati ove necessario con tutte le dovute cure,
- il cemento adoperato è un cemento rispettoso dell’ambiente in quanto il suo utilizzo emette il 50% in meno di diossido di carbonio e che non sono stati introdotti quantitativi aggiuntivi a quelli rimossi dagli interventi pregressi, al contrario.
- che la pavimentazione utilizzata è fortemente drenante per permettere alle acque di percolare nel terreno soggiacente o di essere raccolte nelle apposite vasche di accumulo.

Il comitato “sasso nello stagno” ha poi rimarcato che:

- Dato che la tavola sarà messa a disposizione per studiarla, ci si riserva di rispondere una volta esaminata con cura. \[comunque dal rilievo fotografico le uniche superfici non inverdite sono le rampe e le scale in cemento così come le aere destinate al transito pedonale ricoperte di ghiaia\]
- il rilevamento degli alberi monumentali esistenti è sicuramente un’ottima iniziativa, ma che andrebbe integrata con le disposizioni dell’art.7 della L 10/2013 che estende la monumentalità a tutti gli alberi che compongono la vegetazione arborea della villa,
- il cemento più ecologico è quello che non si usa e che c’erano sicuramente soluzioni costruttive che potevano ridurne considerevolmente l’impiego assecondando maggiormente gli obbiettivi fissati dai Criteri Ambientali Minimi (C.A.M.).
- Seppure la pavimentazione drenante può presentare delle permeabilità migliore dei terreni naturali, non possiede sicuramente lo stesso potenziale biologico e costituisce invariabilmente uno strato di isolamento riguardo alcuni processi di scambio (ossigeno, nutrienti, concimi, etc… ) tra habitat contigui soprattutto in prossimità degli apparati radicali appartenenti ai ficus centrali