---
title: "La Riqualificazione della Villa Comunale di Siderno"
---

Questa pagina tratta specificatamente dei Lavori in corso che mirano a riqualificare la Villa Comunale e dintorni tanta cara ai sidernesi. 
Come al solito ogni vento di cambiamento porta con se maree di osservazioni e commenti


## **PREMESSE**

Sono stati numerosi gli incontri per valutare l’impatto della “**Riqualificazione del Lungomare, della zona fronte Mare e della Villa Comunale della Città Di Siderno**” sull’ambiente, percepito ed effettivo. La  pubblica amministrazione si è mostrata sempre disponibile, ma per la complessità dei temi abbordati, il tempo è sempre venuto a mancare, interrompendo sistematicamente gli [incontri](incontri.qmd), a volte anche nei momenti più promettenti quando inizialmente sembravano solamente disgressioni esplorative.

La redazione di una pagina web si è naturalmente imposta come soluzione ideale per rendere disponibile a tutti le tematiche abbordate che ciascuno può consultare come e quando meglio crede. Il contenuto è facilmente condivisibili nel caso si ritenesse utile farlo, e rappresenta una opportunità di scovare nuove valide prospettive per valutare meglio il valore aggiunto degli interventi presente e futuri dal punto di vista strettamente ambientale, considerato il ruolo di protagonista indefettibile che il tema riveste nel Piano Nazionale della Riprese e Resilienza.

La mole di informazioni recuperate si è addensata col passare del tempo, perciò si è deciso di indicare come leggere il più efficacemente possibili questo minisito. Il comitato "un sasso nello stagno" vuole evidenziare che lo stato di progetto proposto non rispetta le norme che tutelano l'ambiente in questa circostanza. Affermare gratuitamente una cosa del genere sarebbe irrispettoso di tutti coloro che hanno lavorato a cambiare il volto di Siderno con a cuore le migliori intenzioni.  Per iniziare preparati questa lettura, dobbiamo affrontare tematiche non sempre appassionanti.

I primi tre punti concernano la descrizione del quadro normativo, tra l'altro richiamato nella relazione tecnica stessa allegata al progetto.

- [Il Piano Nazionale Di Ripresa e Resilienza](pnrr.qmd).
- [PNRR e la Tutela dei Beni Culturali e del Paesaggio](pnrrbenicp.qmd)
- [La Tutela Del Verde Urbano nell'ambito dell PNRR](pnrr_verde.qmd)


Le due sezioni seguente operano una forma di diagnostica storica dei luoghi condotta con la raccolta e l'analisi d'immagini recuperate da fonti sparse, alcun facilmente identificabili, per cercare di ritracciare l'evoluzione storica del luogo e vedere se può contribuire anche in parte a delineare validi indirizzi.

- [La villa Comunale: Genius Loci](gloci.qmd)
- [Un paese al verde ?](areeverdi.qmd)

La quinta sezione, [la pertinenza del progetto](pertinenza.qmd), è la chiave di volta della contestazione, esamina i motivi principali che, secondo il nostro umile parere, **sono disattesi le prescrizioni contenute nei quadri normativi precedentemente dettagliati**, normalmente invalidando qualsiasi dichiarazione resa quanto al loro rispetto. In primis,  **la diminuzione della consistenza vegetale**, la scintilla scatenante per la quale il comitato si è inizialmente formato! Sorto inizialmente come lieve sospetto si è poi confermato con l'analisi della documentazione pubblicata fino ad oggi come ogni lettore potrà accertarsene indipendentemente. 

La sesta sezione propone delle [varianti](varianti.qmd), perché criticare l'operato di altri è un esercizio semplice al quale alcuni si dilettano per fare parlare di se, o invogliati solo per spirito di contradizione, il comitato vuole andare oltre e tentare di offrire delle soluzioni validi e attuabili, o quanto meno contribuire nella prospettiva di interventi futuri.

Il settimo punto tratta di un [analisi sommaria dei costi](spese.qmd) affrontati, è stato condotto principalmente con lo spirito di quantificare le modifiche proposte e tenere sotto controllo la loro fattibilità cercando di non sforare con soluzioni troppo fantasiose che sarebbero rimaste insoddisfatte in partenza perché non  finanziariamente attuabili.

Tutte queste pagine sono quindi facilmente accessibili dal menu a sinistra sui desktop, sul popup a scomparsa sempre in alto a sinistra sui dispositivi mobili.

Si spera che questi sforzi siano apprezzati per quelli che sono: un tentativo di dialogo tra amministrazione e cittadinanza, in cui il comitato è solo un anello di congiunzione.

[comment]: # (**IL PIANO NAZIONALE DI RIPRESA E RESILIENZA.**)
[comment]: # (**PNRR & LA TUTELLA DEI BENI CULTURALI E DEL PAESAGGIO.**)
[comment]: # (**LA TUTELLA DEL VERDE URBANO NELL'AMBITO DELL PNRR**)
[comment]: # (**LA PERTINENZA DEL PROGETTO**)
[comment]: # (**le varianti**)
[comment]: # (**ANALISI DEI COSTI**)
[comment]: # (**I CHIARIMENTI**)









