---
title: "PNRR, un obbiettivo recondito che sfugge"
---

Il PNRR, come tutti i programmi di finanziamenti precedenti idealmente avrebbero dovuto favorire un sviluppo sinergico del territorio in moda tale da colmare i divari che li separano senza che perdessero la loro identità. Sono sempre stati premiate le iniziative che coinvolgessero un moltitudine di attori a quella promossa da ente unico. 

Al momento però i progetti realizzati grazie al PNRR sembrano  solo tanti interventi sconnessi che consisterebbero solamente a permettere l'iniezione di ingenti fondi per fare ripartire un economia stagnante dovuta:
- l'arresto brutale pandemico, 
- conflitti Ucraina Russia
- e non per ultima la zavorra della politica dell'austerity e del patto di stabilità degli anni precedenti.

Altro punto  a sfavore è che l'economia che si tenta di fare ripartire è sempre quella basata sui precedenti precetti: crescita continua ed inostacolata. Si tirano pure fuori progetti dai cassetti impolverati vecchi di 10 anni fà, si fanno qualche ritocchi superficiali e si mandano in cantiere con la benedizione delle Pubbliche Amministrazioni.


La crisi ambientale che stiamo osservando purtroppo non è solo climatica circoscritta al solo riscaldamento globale. I parametri allarmanti sono vari, nove individuati dalla comunità scientifica in totale, e sei sono stati superati segnando possibilmente la fine dell'olocene iniziato circa 12.000 anni addietro "celebrando" la transizione nell'antropocene.

Il PNRR doveva dare le risorse per attuare il raggiungimento o quanto meno un ravvicinamento ai 17 obiettivi dello sviluppo sostenibile. Ad oggi non è stato sinergicamente pianificato nulla di concreto sul territorio nazionale per affrontare l'emergenza che avrà enorme ripercussioni economiche come l'aveva già segnalato un paio di anni fa l'economista Jeremy Rifkin.

Se oggi col PNRR si danno soluzioni a problemi d'ieri e non a quelli di domani, l'utilizzo dei fondi è allora fallimentare.



