---
title: "PNRR e la tutela dei Beni Culturali e del Paesaggio"

---

L’intervento di recupero della Villa Comunale poteva attingere a due tipologie d'investimento:

1. il programma per valorizzare l'identità di luoghi: parchi e giardini storici (missione 1 comparto 3 investimento 2.3), 
2. il secondo con un progetto di rigenerazione urbana, volti a ridurre situazioni di emarginazione e degrado sociale (missione 5 comparto 2 investimento 2.1)

Il primo,  per le qualità che la villetta presentava come giardino storico, sembrava confezionato su misura, purtroppo l’art.6 co.3 dell’avviso pubblico determinava come soggetto ammissibile solo coloro che:

_Ai fini dell’ammissibilità saranno ritenuti validi sia i provvedimenti di tutela diretta sul giardino, sia quelli sull’immobile del quale il giardino è pertinenza, purché risulti evidente la sua rilevanza sotto il profilo storico-artistico._ **_Nel caso di beni di cui all’art. 10 comma 1 del D.Lgs. n. 42/2004 non saranno presi in considerazione quelli tutelati ope legis_** _o con procedimento di verifica dell’interesse culturale ai sensi dell’art. 12 del sopracitato decreto legislativo ancora non concluso_

In parole povere la villetta ricadrebbe automaticamente sotto la tutela dei beni culturali solo perché realizzata da più di 70 anni e perché di proprietà dello stato e non per motivi qualitativi intrinsechi alla sua peculiarità artistica o botanica, se esistono non sono state ancora ufficialmente evidenziate, attraverso una procedura di valutazione condotta dalla Soprintendenza.

Rimane allora, per finanziare l’intervento, la seconda opzione; il programma riservati ai progetti di rigenerazione urbana. L'opportunità è ottima e probabilmente irrepetibile nel prossimo futuro, l’amministrazione comunale giustamente la coglie ed ottiene così il finanziamento per:

"LA RIGENERAZIONE DEGLI SPAZI URBANI PUBBLICI RICADENTI ALL’INTERNO DEL CENTRO ABITATO DI SIDERNO MARINA \*VIA DIVERSE\* RIQUALIFICAZIONE AREE VERDI." Per un importo complessivo di € 1.3 mln (CUP: I15F21000410001 – CIG: 9915740780).

La scheda descrittiva assegnata alla proposta di progetto disponibile sul sito “[opencup.gov.it](https://www.opencup.gov.it/portale/it/web/opencup/home/progetto/-/cup/I15F21000410001)” classifica però tutt’oggi il progetto nella tipologia RESTAURO e nella categoria "VERDE PUBBLICO".

Se la qualifica di "restauro" abbia una connotazione vincolante e se la categoria "verde pubblico" determina un indirizzo preponderante de perseguire, pare che rimanga sempre l’onere alla stazione appaltante di conservarne le caratteristiche che contraddistinguono la natura stessa della Villa Comunale. 
In questo caso saggia sarebbe l'osservanza delle prescrizioni contenute nelle **LINEE GUIDA E NORME TECNICHE PER IL RESTAURO DEI GIARDINI STORICI** curato dall’ APGI - ASSOCIAZIONE PARCHI E GIARDINI D’ITALIA per il Ministero della Cultura. Sono state redatte appositamente per trattare tutti i tipi di parchi e giardini storici, dai più piccoli ai più principeschi, che rientrano nei finanziamenti del primo gruppo, esse contengono preziosi suggerimenti che possono definitivamente applicarsi alla gestione della nostra Villa Comunale, compresi i dettagli di tutte le fasi d’intervento sul verde, e gli eccellenti metodi di diagnostica preliminare indispensabili per un esito di successo.