---
title: "Il Piano Nazionale di Ripresa e Resilienza"

---

L'ambiente è oramai la priorità numero uno in tutte le programmazione a lungo termine ed è importante evidenziare la ratio soggiacente alla programmazione del PNRR; elencando gli obiettivi perseguiti:

- l'adattamento e la mitigazione del cambiamento climatico,
- favorire l'economia circolare,
- prevenire o ridurre l'inquinamento e
- proteggere o ripristinare la biodiversità e gli ecosistemi.

Per raggiungere questi scopi vengono finanziati degli investimenti a condizione che vengono rispettate delle normative di riferimento specifiche per ogni categoria d’investimento. Gli interventi sul **verde** ricomprendono spesso le seguenti disposizioni generali:

- comunitarie (Natura 2000, Direttive 92/43/CEE “Habitat”, 2009/147/CE “Uccelli”, ...),
- nazionali (testo unico ambientale D.lgs 152/06, Criteri Ambientali Minimi DM 63/2020, L.113/192 e successiva L. n. 10/2013 “norme per lo sviluppo degli spazi verdi urbani”) e
- regionali ove applicabili (LR Calabria 56/2019 e 7/2024)

Queste normative sono inderogabili per l'ottenimento del finanziamento. Se per esempio nell'amministrazione ordinaria l'applicazione della legge 10/2013 era discrezionale, **diventa obbligatoria nel contesto di un’opera finanziata dal PNRR**.